const Frases  = {
    lista: [
        { mandarin: "你好", pinyin: "Nǐ hǎo", spanish: "Hola" },
        { mandarin: "谢谢", pinyin: "Xièxie", spanish: "Gracias" },
        { mandarin: "我爱你", pinyin: "Wǒ ài nǐ", spanish: "Te amo" },
        { mandarin: "朋友", pinyin: "Péngyǒu", spanish: "Amigo" },
             { mandarin: "的", pinyin: "de", spanish: "(partícula posesiva)" },
        { mandarin: "是", pinyin: "shì", spanish: "ser" },
        { mandarin: "不", pinyin: "bù", spanish: "no" },
        { mandarin: "了", pinyin: "le", spanish: "(partícula de tiempo pasado)" },
        { mandarin: "人", pinyin: "rén", spanish: "persona" },
        { mandarin: "我", pinyin: "wǒ", spanish: "yo" },
        { mandarin: "在", pinyin: "zài", spanish: "en/estar" },
        { mandarin: "有", pinyin: "yǒu", spanish: "tener" },
        { mandarin: "他", pinyin: "tā", spanish: "él" },
        { mandarin: "这", pinyin: "zhè", spanish: "este" },
        { mandarin: "中", pinyin: "zhōng", spanish: "centro/China" },
        { mandarin: "大", pinyin: "dà", spanish: "grande" },
        { mandarin: "来", pinyin: "lái", spanish: "venir" },
        { mandarin: "上", pinyin: "shàng", spanish: "arriba" },
        { mandarin: "个", pinyin: "gè", spanish: "(clasificador)" },
        { mandarin: "到", pinyin: "dào", spanish: "llegar" },
        { mandarin: "说", pinyin: "shuō", spanish: "hablar" },
        { mandarin: "们", pinyin: "men", spanish: "(plural para pronombres)" },
        { mandarin: "为", pinyin: "wèi", spanish: "para/por" },
        { mandarin: "子", pinyin: "zi", spanish: "hijo/partícula" },
        { mandarin: "和", pinyin: "hé", spanish: "y" },
        { mandarin: "你", pinyin: "nǐ", spanish: "tú" },
        { mandarin: "地", pinyin: "de", spanish: "(partícula adverbial)" },
        { mandarin: "出", pinyin: "chū", spanish: "salir" },
        { mandarin: "道", pinyin: "dào", spanish: "camino" },
        { mandarin: "也", pinyin: "yě", spanish: "también" },
        { mandarin: "时", pinyin: "shí", spanish: "tiempo" },
        { mandarin: "年", pinyin: "nián", spanish: "año" },
        { mandarin: "得", pinyin: "de", spanish: "(partícula)" },
        { mandarin: "就", pinyin: "jiù", spanish: "entonces" },
        { mandarin: "那", pinyin: "nà", spanish: "ese/aquel" },
        { mandarin: "要", pinyin: "yào", spanish: "querer/necesitar" },
        { mandarin: "下", pinyin: "xià", spanish: "abajo" },
        { mandarin: "以", pinyin: "yǐ", spanish: "usar" },
        { mandarin: "生", pinyin: "shēng", spanish: "nacer/vida" },
        { mandarin: "会", pinyin: "huì", spanish: "saber/reunión" },
        { mandarin: "自", pinyin: "zì", spanish: "desde" },
        { mandarin: "着", pinyin: "zhe", spanish: "(partícula continua)" },
        { mandarin: "去", pinyin: "qù", spanish: "ir" },
        { mandarin: "之", pinyin: "zhī", spanish: "de/esto" },
        { mandarin: "过", pinyin: "guò", spanish: "(experiencia pasada)" },
        { mandarin: "家", pinyin: "jiā", spanish: "familia/casa" },
        { mandarin: "学", pinyin: "xué", spanish: "estudiar" },
        { mandarin: "对", pinyin: "duì", spanish: "correcto/hacia" },
        { mandarin: "可", pinyin: "kě", spanish: "poder" },
        { mandarin: "她", pinyin: "tā", spanish: "ella" },
        { mandarin: "里", pinyin: "lǐ", spanish: "dentro" },
        { mandarin: "后", pinyin: "hòu", spanish: "después" },
        
        // Caracteres comunes (51-200) - Ejemplos clave:
        { mandarin: "小", pinyin: "xiǎo", spanish: "pequeño" },
        { mandarin: "心", pinyin: "xīn", spanish: "corazón" },
        { mandarin: "国", pinyin: "guó", spanish: "país" },
        { mandarin: "好", pinyin: "hǎo", spanish: "bueno" },
        { mandarin: "吗", pinyin: "ma", spanish: "(partícula de pregunta)" },
        { mandarin: "多", pinyin: "duō", spanish: "mucho" },
        { mandarin: "天", pinyin: "tiān", spanish: "cielo/día" },
        { mandarin: "手", pinyin: "shǒu", spanish: "mano" },
        { mandarin: "水", pinyin: "shuǐ", spanish: "agua" },
        { mandarin: "电", pinyin: "diàn", spanish: "electricidad" },
        { mandarin: "门", pinyin: "mén", spanish: "puerta" },
        { mandarin: "开", pinyin: "kāi", spanish: "abrir" },
        { mandarin: "见", pinyin: "jiàn", spanish: "ver" },
        { mandarin: "回", pinyin: "huí", spanish: "regresar" },
        { mandarin: "什", pinyin: "shén", spanish: "qué" },
        { mandarin: "么", pinyin: "me", spanish: "(partícula)" },
        { mandarin: "点", pinyin: "diǎn", spanish: "punto/hora" },
        { mandarin: "吃", pinyin: "chī", spanish: "comer" },
        { mandarin: "喝", pinyin: "hē", spanish: "beber" },
        { mandarin: "走", pinyin: "zǒu", spanish: "caminar" },
        { mandarin: "买", pinyin: "mǎi", spanish: "comprar" },
        { mandarin: "钱", pinyin: "qián", spanish: "dinero" },
        { mandarin: "日", pinyin: "rì", spanish: "sol/día" },
        { mandarin: "月", pinyin: "yuè", spanish: "luna/mes" },
        { mandarin: "火", pinyin: "huǒ", spanish: "fuego" },
        { mandarin: "山", pinyin: "shān", spanish: "montaña" },
        { mandarin: "木", pinyin: "mù", spanish: "madera" },
        { mandarin: "口", pinyin: "kǒu", spanish: "boca" },
        { mandarin: "女", pinyin: "nǚ", spanish: "mujer" },
        { mandarin: "子", pinyin: "zǐ", spanish: "niño" },
        { mandarin: "车", pinyin: "chē", spanish: "vehículo" },
        { mandarin: "书", pinyin: "shū", spanish: "libro" },
        { mandarin: "字", pinyin: "zì", spanish: "carácter" },
        { mandarin: "星期一", pinyin: "xīngqī yī", spanish: "lunes" },
{ mandarin: "星期二", pinyin: "xīngqī èr", spanish: "martes" },
{ mandarin: "星期三", pinyin: "xīngqī sān", spanish: "miércoles" },
{ mandarin: "星期四", pinyin: "xīngqī sì", spanish: "jueves" },
{ mandarin: "星期五", pinyin: "xīngqī wǔ", spanish: "viernes" },
{ mandarin: "星期六", pinyin: "xīngqī liù", spanish: "sábado" },
{ mandarin: "星期日", pinyin: "xīngqī rì", spanish: "domingo" },
{ mandarin: "一月", pinyin: "yī yuè", spanish: "enero" },
{ mandarin: "二月", pinyin: "èr yuè", spanish: "febrero" },
{ mandarin: "三月", pinyin: "sān yuè", spanish: "marzo" },
{ mandarin: "四月", pinyin: "sì yuè", spanish: "abril" },
{ mandarin: "五月", pinyin: "wǔ yuè", spanish: "mayo" },
{ mandarin: "六月", pinyin: "liù yuè", spanish: "junio" },
{ mandarin: "七月", pinyin: "qī yuè", spanish: "julio" },
{ mandarin: "八月", pinyin: "bā yuè", spanish: "agosto" },
{ mandarin: "九月", pinyin: "jiǔ yuè", spanish: "septiembre" },
{ mandarin: "十月", pinyin: "shí yuè", spanish: "octubre" },
{ mandarin: "十一月", pinyin: "shí yī yuè", spanish: "noviembre" },
{ mandarin: "十二月", pinyin: "shí èr yuè", spanish: "diciembre" },
{ mandarin: "零", pinyin: "Líng", spanish: "zero" },
{ mandarin: "四", pinyin: "sì", spanish: "cuatro" },
{ mandarin: "五", pinyin: "wǔ", spanish: "cinco" },
{ mandarin: "六", pinyin: "liù", spanish: "seis" },
{ mandarin: "七", pinyin: "qī", spanish: "siete" },
{ mandarin: "八", pinyin: "bā", spanish: "ocho" },
{ mandarin: "九", pinyin: "jiǔ", spanish: "nueve" },
{ mandarin: "十四", pinyin: "shí sì", spanish: "catorce" },
{ mandarin: "十五", pinyin: "shí wǔ", spanish: "quince" },
{ mandarin: "十七", pinyin: "shí qī", spanish: "diecisiete" },
{ mandarin: "十八", pinyin: "shí bā", spanish: "dieciocho" },
{ mandarin: "十九", pinyin: "shí jiǔ", spanish: "diecinueve" },
{ mandarin: "二十", pinyin: "èr shí", spanish: "veinte" },
{ mandarin: "红色", pinyin: "hóng sè", spanish: "rojo" },
{ mandarin: "蓝色", pinyin: "lán sè", spanish: "azul" },
{ mandarin: "黄色", pinyin: "huáng sè", spanish: "amarillo" },
{ mandarin: "绿色", pinyin: "lǜ sè", spanish: "verde" },
{ mandarin: "黑色", pinyin: "hēi sè", spanish: "negro" },
{ mandarin: "白色", pinyin: "bái sè", spanish: "blanco" },
{ mandarin: "灰色", pinyin: "huī sè", spanish: "gris" },
{ mandarin: "棕色", pinyin: "zōng sè", spanish: "marrón" },
{ mandarin: "粉色", pinyin: "fěn sè", spanish: "rosado" },
{ mandarin: "橙色", pinyin: "chéng sè", spanish: "naranja" },
{ mandarin: "紫色", pinyin: "zǐ sè", spanish: "morado" },
{ mandarin: "金色", pinyin: "jīn sè", spanish: "dorado" },
{ mandarin: "银色", pinyin: "yín sè", spanish: "plateado" },
{ mandarin: "米色", pinyin: "mǐ sè", spanish: "beige" },
{ mandarin: "天蓝色", pinyin: "tiān lán sè", spanish: "celeste" },
{ mandarin: "苹果", pinyin: "píng guǒ", spanish: "manzana" },
{ mandarin: "香蕉", pinyin: "xiāng jiāo", spanish: "plátano" },
{ mandarin: "橙子", pinyin: "chéng zi", spanish: "naranja" },
{ mandarin: "葡萄", pinyin: "pú táo", spanish: "uva" },
{ mandarin: "草莓", pinyin: "cǎo méi", spanish: "fresa" },
{ mandarin: "西瓜", pinyin: "xī guā", spanish: "sandía" },
{ mandarin: "哈密瓜", pinyin: "hā mì guā", spanish: "melón" },
{ mandarin: "柠檬", pinyin: "níng méng", spanish: "limón" },
{ mandarin: "桃子", pinyin: "táo zi", spanish: "durazno" },
{ mandarin: "梨", pinyin: "lí", spanish: "pera" },
{ mandarin: "樱桃", pinyin: "yīng táo", spanish: "cereza" },
{ mandarin: "李子", pinyin: "lǐ zi", spanish: "ciruela" },
{ mandarin: "蓝莓", pinyin: "lán méi", spanish: "arándano" },
{ mandarin: "木瓜", pinyin: "mù guā", spanish: "papaya" },
{ mandarin: "火龙果", pinyin: "huǒ lóng guǒ", spanish: "pitahaya" },
{ mandarin: "芒果", pinyin: "máng guǒ", spanish: "mango" },
{ mandarin: "椰子", pinyin: "yē zi", spanish: "coco" },
{ mandarin: "石榴", pinyin: "shí liú", spanish: "granada" },
{ mandarin: "枇杷", pinyin: "pí pá", spanish: "níspero" },
{ mandarin: "山竹", pinyin: "shān zhú", spanish: "mangostán" },
{ mandarin: "甘蔗", pinyin: "gān zhè", spanish: "caña de azúcar" },
{ mandarin: "柚子", pinyin: "yòu zi", spanish: "pomelo" },
{ mandarin: "龙眼", pinyin: "lóng yǎn", spanish: "longán" },
{ mandarin: "荔枝", pinyin: "lì zhī", spanish: "litchi" },
{ mandarin: "猕猴桃", pinyin: "mí hóu táo", spanish: "kiwi" },
{ mandarin: "无花果", pinyin: "wú huā guǒ", spanish: "higo" },
{ mandarin: "桑葚", pinyin: "sāng shèn", spanish: "mora" },
{ mandarin: "番石榴", pinyin: "fān shí liú", spanish: "guayaba" },
{ mandarin: "柿子", pinyin: "shì zi", spanish: "caqui" },
{ mandarin: "椰枣", pinyin: "yē zǎo", spanish: "dátil" },
{ mandarin: "胡萝卜", pinyin: "hú luó bo", spanish: "zanahoria" },
{ mandarin: "西红柿", pinyin: "xī hóng shì", spanish: "tomate" },
{ mandarin: "黄瓜", pinyin: "huáng guā", spanish: "pepino" },
{ mandarin: "土豆", pinyin: "tǔ dòu", spanish: "papa" },
{ mandarin: "洋葱", pinyin: "yáng cōng", spanish: "cebolla" },
{ mandarin: "白菜", pinyin: "bái cài", spanish: "repollo chino" },
{ mandarin: "菠菜", pinyin: "bō cài", spanish: "espinaca" },
{ mandarin: "生菜", pinyin: "shēng cài", spanish: "lechuga" },
{ mandarin: "芹菜", pinyin: "qín cài", spanish: "apio" },
{ mandarin: "蘑菇", pinyin: "mó gu", spanish: "champiñón" },
{ mandarin: "辣椒", pinyin: "là jiāo", spanish: "chile/pimiento picante" },
{ mandarin: "青椒", pinyin: "qīng jiāo", spanish: "pimiento verde" },
{ mandarin: "红椒", pinyin: "hóng jiāo", spanish: "pimiento rojo" },
{ mandarin: "南瓜", pinyin: "nán guā", spanish: "calabaza" },
{ mandarin: "茄子", pinyin: "qié zi", spanish: "berenjena" },
{ mandarin: "豆角", pinyin: "dòu jiǎo", spanish: "judía verde" },
{ mandarin: "西兰花", pinyin: "xī lán huā", spanish: "brócoli" },
{ mandarin: "菜花", pinyin: "cài huā", spanish: "coliflor" },
{ mandarin: "蒜", pinyin: "suàn", spanish: "ajo" },
{ mandarin: "姜", pinyin: "jiāng", spanish: "jengibre" },
{ mandarin: "狗", pinyin: "gǒu", spanish: "perro" },
{ mandarin: "猫", pinyin: "māo", spanish: "gato" },
{ mandarin: "鸟", pinyin: "niǎo", spanish: "pájaro" },
{ mandarin: "鱼", pinyin: "yú", spanish: "pez" },
{ mandarin: "马", pinyin: "mǎ", spanish: "caballo" },
{ mandarin: "牛", pinyin: "niú", spanish: "vaca" },
{ mandarin: "羊", pinyin: "yáng", spanish: "oveja/cabra" },
{ mandarin: "猪", pinyin: "zhū", spanish: "cerdo" },
{ mandarin: "鸡", pinyin: "jī", spanish: "gallina/pollo" },
{ mandarin: "鸭", pinyin: "yā", spanish: "pato" },
{ mandarin: "兔子", pinyin: "tù zi", spanish: "conejo" },
{ mandarin: "老虎", pinyin: "lǎo hǔ", spanish: "tigre" },
{ mandarin: "狮子", pinyin: "shī zi", spanish: "león" },
{ mandarin: "熊", pinyin: "xióng", spanish: "oso" },
{ mandarin: "大象", pinyin: "dà xiàng", spanish: "elefante" },
{ mandarin: "猴子", pinyin: "hóu zi", spanish: "mono" },
{ mandarin: "狼", pinyin: "láng", spanish: "lobo" },
{ mandarin: "狐狸", pinyin: "hú li", spanish: "zorro" },
{ mandarin: "蛇", pinyin: "shé", spanish: "serpiente" },
{ mandarin: "青蛙", pinyin: "qīng wā", spanish: "rana" },
{ mandarin: "熊猫", pinyin: "xióng māo", spanish: "panda" },
{ mandarin: "老鼠", pinyin: "lǎo shǔ", spanish: "ratón" },
{ mandarin: "松鼠", pinyin: "sōng shǔ", spanish: "ardilla" },
{ mandarin: "海豚", pinyin: "hǎi tún", spanish: "delfín" },
{ mandarin: "鲸鱼", pinyin: "jīng yú", spanish: "ballena" },
{ mandarin: "企鹅", pinyin: "qǐ é", spanish: "pingüino" },
{ mandarin: "骆驼", pinyin: "luò tuo", spanish: "camello" },
{ mandarin: "袋鼠", pinyin: "dài shǔ", spanish: "canguro" },
{ mandarin: "乌龟", pinyin: "wū guī", spanish: "tortuga" },
{ mandarin: "蚂蚁", pinyin: "mǎ yǐ", spanish: "hormiga" },
{ mandarin: "是", pinyin: "shì", spanish: "ser" },
{ mandarin: "有", pinyin: "yǒu", spanish: "tener" },
{ mandarin: "去", pinyin: "qù", spanish: "ir" },
{ mandarin: "来", pinyin: "lái", spanish: "venir" },
{ mandarin: "看", pinyin: "kàn", spanish: "ver" },
{ mandarin: "听", pinyin: "tīng", spanish: "escuchar" },
{ mandarin: "说", pinyin: "shuō", spanish: "decir" },
{ mandarin: "做", pinyin: "zuò", spanish: "hacer" },
{ mandarin: "吃", pinyin: "chī", spanish: "comer" },
{ mandarin: "喝", pinyin: "hē", spanish: "beber" },
{ mandarin: "想", pinyin: "xiǎng", spanish: "pensar/querer" },
{ mandarin: "知道", pinyin: "zhī dào", spanish: "saber" },
{ mandarin: "喜欢", pinyin: "xǐ huān", spanish: "gustar" },
{ mandarin: "爱", pinyin: "ài", spanish: "amar" },
{ mandarin: "工作", pinyin: "gōng zuò", spanish: "trabajar" },
{ mandarin: "学习", pinyin: "xué xí", spanish: "estudiar" },
{ mandarin: "睡觉", pinyin: "shuì jiào", spanish: "dormir" },
{ mandarin: "起床", pinyin: "qǐ chuáng", spanish: "levantarse" },
{ mandarin: "穿", pinyin: "chuān", spanish: "vestir" },
{ mandarin: "买", pinyin: "mǎi", spanish: "comprar" },
{ mandarin: "卖", pinyin: "mài", spanish: "vender" },
{ mandarin: "开", pinyin: "kāi", spanish: "abrir/conducir" },
{ mandarin: "关", pinyin: "guān", spanish: "cerrar" },
{ mandarin: "写", pinyin: "xiě", spanish: "escribir" },
{ mandarin: "读", pinyin: "dú", spanish: "leer" },
{ mandarin: "等", pinyin: "děng", spanish: "esperar" },
{ mandarin: "坐", pinyin: "zuò", spanish: "sentarse" },
{ mandarin: "站", pinyin: "zhàn", spanish: "estar de pie" },
{ mandarin: "跑", pinyin: "pǎo", spanish: "correr" },
{ mandarin: "走", pinyin: "zǒu", spanish: "caminar" },
{ mandarin: "跳", pinyin: "tiào", spanish: "saltar" },
{ mandarin: "洗", pinyin: "xǐ", spanish: "lavar" },
{ mandarin: "笑", pinyin: "xiào", spanish: "reír" },
{ mandarin: "哭", pinyin: "kū", spanish: "llorar" },
{ mandarin: "帮助", pinyin: "bāng zhù", spanish: "ayudar" },
{ mandarin: "用", pinyin: "yòng", spanish: "usar" },
{ mandarin: "找", pinyin: "zhǎo", spanish: "buscar" },
{ mandarin: "忘记", pinyin: "wàng jì", spanish: "olvidar" },
{ mandarin: "记得", pinyin: "jì de", spanish: "recordar" },
{ mandarin: "开始", pinyin: "kāi shǐ", spanish: "empezar" },
{ mandarin: "结束", pinyin: "jié shù", spanish: "terminar" },
{ mandarin: "热", pinyin: "rè", spanish: "caliente" },  
{ mandarin: "大", pinyin: "dà", spanish: "grande" },  
{ mandarin: "高", pinyin: "gāo", spanish: "alto (estatura)" },  
{ mandarin: "快", pinyin: "kuài", spanish: "rápido" },  
{ mandarin: "强", pinyin: "qiáng", spanish: "fuerte" },  
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },  
{ mandarin: "新", pinyin: "xīn", spanish: "nuevo" },  
{ mandarin: "干净", pinyin: "gānjìng", spanish: "limpio" },  
{ mandarin: "软", pinyin: "ruǎn", spanish: "blando" },  
{ mandarin: "轻", pinyin: "qīng", spanish: "ligero" },  
{ mandarin: "亮", pinyin: "liàng", spanish: "brillante" },  
{ mandarin: "湿", pinyin: "shī", spanish: "mojado" },  
{ mandarin: "健康", pinyin: "jiànkāng", spanish: "saludable" },  
{ mandarin: "高兴", pinyin: "gāoxìng", spanish: "feliz" },  
{ mandarin: "满", pinyin: "mǎn", spanish: "lleno" },  
{ mandarin: "开", pinyin: "kāi", spanish: "abierto" },  
{ mandarin: "白天", pinyin: "báitiān", spanish: "día" },  
{ mandarin: "年轻", pinyin: "niánqīng", spanish: "joven" },  
{ mandarin: "松", pinyin: "sōng", spanish: "suelto" },  
{ mandarin: "香", pinyin: "xiāng", spanish: "aromático" },  
{ mandarin: "安全", pinyin: "ānquán", spanish: "seguro" },  
{ mandarin: "富裕", pinyin: "fùyù", spanish: "rico" },  
{ mandarin: "光滑", pinyin: "guānghuá", spanish: "liso" },  
{ mandarin: "酸", pinyin: "suān", spanish: "agrio" },  
{ mandarin: "辣", pinyin: "là", spanish: "picante" },  
{ mandarin: "简单", pinyin: "jiǎndān", spanish: "simple" },  
{ mandarin: "安静", pinyin: "ānjìng", spanish: "silencioso" },  
{ mandarin: "胖", pinyin: "pàng", spanish: "gordo" },  
{ mandarin: "长", pinyin: "cháng", spanish: "largo" },  
{ mandarin: "粗", pinyin: "cū", spanish: "grueso" },  
{ mandarin: "早", pinyin: "zǎo", spanish: "temprano" },  
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },  
{ mandarin: "忙", pinyin: "máng", spanish: "ocupado" },  
{ mandarin: "美", pinyin: "měi", spanish: "hermoso" },  
{ mandarin: "真", pinyin: "zhēn", spanish: "verdadero" },  
{ mandarin: "朋友", pinyin: "péngyou", spanish: "amigo" },  
{ mandarin: "胜利", pinyin: "shènglì", spanish: "victoria" },  
{ mandarin: "勇敢", pinyin: "yǒnggǎn", spanish: "valiente" },  
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },  
{ mandarin: "活", pinyin: "huó", spanish: "vivo" },  
{ mandarin: "深", pinyin: "shēn", spanish: "profundo" },  
{ mandarin: "宽", pinyin: "kuān", spanish: "ancho" },  
{ mandarin: "暖", pinyin: "nuǎn", spanish: "tibio" },  
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },  
{ mandarin: "爱", pinyin: "ài", spanish: "amor" },  
{ mandarin: "八", pinyin: "bā", spanish: "ocho" },  
{ mandarin: "爸爸", pinyin: "bàba", spanish: "papá" },  
{ mandarin: "杯子", pinyin: "bēizi", spanish: "vaso/taza" },  
{ mandarin: "北京", pinyin: "Běijīng", spanish: "Pekín" },  
{ mandarin: "本", pinyin: "běn", spanish: "libro" },  
{ mandarin: "不客气", pinyin: "bú kèqi", spanish: "de nada" },  
{ mandarin: "不", pinyin: "bù", spanish: "no" },  
{ mandarin: "菜", pinyin: "cài", spanish: "plato" },  
{ mandarin: "茶", pinyin: "chá", spanish: "té" },  
{ mandarin: "吃", pinyin: "chī", spanish: "comer" },  
{ mandarin: "出租车", pinyin: "chūzūchē", spanish: "taxi" },  
{ mandarin: "打电话", pinyin: "dǎ diànhuà", spanish: "llamar por teléfono" },  
{ mandarin: "大", pinyin: "dà", spanish: "grande" },  
{ mandarin: "的", pinyin: "de", spanish: "de" },  
{ mandarin: "点", pinyin: "diǎn", spanish: "hora" },  
{ mandarin: "电脑", pinyin: "diànnǎo", spanish: "computadora" },  
{ mandarin: "电视", pinyin: "diànshì", spanish: "televisor" },  
{ mandarin: "电影", pinyin: "diànyǐng", spanish: "película" },  
{ mandarin: "东西", pinyin: "dōngxi", spanish: "cosa" },  
{ mandarin: "都", pinyin: "dōu", spanish: "todo" },  
{ mandarin: "读", pinyin: "dú", spanish: "leer" },  
{ mandarin: "对不起", pinyin: "duìbuqǐ", spanish: "perdón" },  
{ mandarin: "多", pinyin: "duō", spanish: "mucho" },  
{ mandarin: "多少", pinyin: "duōshǎo", spanish: "cuánto" },  
{ mandarin: "儿子", pinyin: "érzi", spanish: "hijo" },  
{ mandarin: "饭店", pinyin: "fàndiàn", spanish: "restaurante" },  
{ mandarin: "飞机", pinyin: "fēijī", spanish: "avión" },  
{ mandarin: "分钟", pinyin: "fēnzhōng", spanish: "minuto" },  
{ mandarin: "高兴", pinyin: "gāoxìng", spanish: "feliz" },  
{ mandarin: "个", pinyin: "gè", spanish: "unidad" },  
{ mandarin: "工作", pinyin: "gōngzuò", spanish: "trabajo" },  
{ mandarin: "狗", pinyin: "gǒu", spanish: "perro" },  
{ mandarin: "汉语", pinyin: "Hànyǔ", spanish: "idioma chino" },  
{ mandarin: "新鲜", pinyin: "xīnxiān", spanish: "fresco" },  
{ mandarin: "上升", pinyin: "shàngshēng", spanish: "ascender" },  
{ mandarin: "开始", pinyin: "kāishǐ", spanish: "comenzar" },  
{ mandarin: "光明", pinyin: "guāngmíng", spanish: "luminoso" },  
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },  
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },  
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },
{ mandarin: "冷", pinyin: "lěng", spanish: "frío" },  
{ mandarin: "小", pinyin: "xiǎo", spanish: "pequeño" },  
{ mandarin: "矮", pinyin: "ǎi", spanish: "bajo (estatura)" },  
{ mandarin: "慢", pinyin: "màn", spanish: "lento" },  
{ mandarin: "弱", pinyin: "ruò", spanish: "débil" },  
{ mandarin: "咸", pinyin: "xián", spanish: "salado" },  
{ mandarin: "旧", pinyin: "jiù", spanish: "viejo" },  
{ mandarin: "脏", pinyin: "zāng", spanish: "sucio" },  
{ mandarin: "硬", pinyin: "yìng", spanish: "duro" },  
{ mandarin: "重", pinyin: "zhòng", spanish: "pesado" },  
{ mandarin: "暗", pinyin: "àn", spanish: "oscuro" },  
{ mandarin: "干", pinyin: "gān", spanish: "seco" },  
{ mandarin: "生病", pinyin: "shēngbìng", spanish: "enfermo" },  
{ mandarin: "难过", pinyin: "nánguò", spanish: "triste" },  
{ mandarin: "空", pinyin: "kōng", spanish: "vacío" },  
{ mandarin: "关", pinyin: "guān", spanish: "cerrado" },  
{ mandarin: "晚上", pinyin: "wǎnshàng", spanish: "noche" },  
{ mandarin: "老", pinyin: "lǎo", spanish: "viejo (edad)" },  
{ mandarin: "紧", pinyin: "jǐn", spanish: "apretado" },  
{ mandarin: "臭", pinyin: "chòu", spanish: "maloliente" },  
{ mandarin: "危险", pinyin: "wēixiǎn", spanish: "peligroso" },  
{ mandarin: "贫穷", pinyin: "pínqióng", spanish: "pobre" },  
{ mandarin: "粗糙", pinyin: "cūcāo", spanish: "áspero" },  
{ mandarin: "淡", pinyin: "dàn", spanish: "soso" },  
{ mandarin: "复杂", pinyin: "fùzá", spanish: "complicado" },  
{ mandarin: "吵闹", pinyin: "chǎonào", spanish: "ruidoso" },  
{ mandarin: "瘦", pinyin: "shòu", spanish: "delgado" },  
{ mandarin: "短", pinyin: "duǎn", spanish: "corto" },  
{ mandarin: "细", pinyin: "xì", spanish: "fino" },  
{ mandarin: "晚", pinyin: "wǎn", spanish: "tarde" },  
{ mandarin: "闲", pinyin: "xián", spanish: "libre (ocupación)" },  
{ mandarin: "丑", pinyin: "chǒu", spanish: "feo" },  
{ mandarin: "假", pinyin: "jiǎ", spanish: "falso" },  
{ mandarin: "敌人", pinyin: "dírén", spanish: "enemigo" },  
{ mandarin: "失败", pinyin: "shībài", spanish: "fracaso" },  
{ mandarin: "胆小", pinyin: "dǎnxiǎo", spanish: "cobarde" },  
{ mandarin: "死", pinyin: "sǐ", spanish: "muerto" },  
{ mandarin: "浅", pinyin: "qiǎn", spanish: "superficial" },  
{ mandarin: "窄", pinyin: "zhǎi", spanish: "estrecho" },  
{ mandarin: "凉", pinyin: "liáng", spanish: "fresco (temperatura)" },  
{ mandarin: "腐烂", pinyin: "fǔlàn", spanish: "podrido" },  
{ mandarin: "下降", pinyin: "xiàjiàng", spanish: "descender" },  
{ mandarin: "结束", pinyin: "jiéshù", spanish: "terminar" },  
{ mandarin: "黑暗", pinyin: "hēi'àn", spanish: "oscuro" },
{ mandarin: "你好", pinyin: "nǐ hǎo", spanish: "hola" },  
{ mandarin: "谢谢", pinyin: "xièxie", spanish: "gracias" },  
{ mandarin: "再见", pinyin: "zàijiàn", spanish: "adiós" },  
{ mandarin: "朋友", pinyin: "péngyou", spanish: "amigo" },  
{ mandarin: "家庭", pinyin: "jiātíng", spanish: "familia" },  
{ mandarin: "学校", pinyin: "xuéxiào", spanish: "escuela" },  
{ mandarin: "工作", pinyin: "gōngzuò", spanish: "trabajo" },  
{ mandarin: "时间", pinyin: "shíjiān", spanish: "tiempo" },  
{ mandarin: "今天", pinyin: "jīntiān", spanish: "hoy" },  
{ mandarin: "明天", pinyin: "míngtiān", spanish: "mañana" },  
{ mandarin: "昨天", pinyin: "zuótiān", spanish: "ayer" },  
{ mandarin: "现在", pinyin: "xiànzài", spanish: "ahora" },  
{ mandarin: "未来", pinyin: "wèilái", spanish: "futuro" },  
{ mandarin: "过去", pinyin: "guòqù", spanish: "pasado" },  
{ mandarin: "天气", pinyin: "tiānqì", spanish: "clima" },  
{ mandarin: "太阳", pinyin: "tàiyáng", spanish: "sol" },  
{ mandarin: "月亮", pinyin: "yuèliang", spanish: "luna" },  
{ mandarin: "星星", pinyin: "xīngxing", spanish: "estrella" },  
{ mandarin: "城市", pinyin: "chéngshì", spanish: "ciudad" },  
{ mandarin: "农村", pinyin: "nóngcūn", spanish: "campo" },  
{ mandarin: "国家", pinyin: "guójiā", spanish: "país" },  
{ mandarin: "文化", pinyin: "wénhuà", spanish: "cultura" },  
{ mandarin: "语言", pinyin: "yǔyán", spanish: "idioma" },  
{ mandarin: "音乐", pinyin: "yīnyuè", spanish: "música" },  
{ mandarin: "电影", pinyin: "diànyǐng", spanish: "película" },  
{ mandarin: "电视", pinyin: "diànshì", spanish: "televisión" },  
{ mandarin: "电脑", pinyin: "diànnǎo", spanish: "computadora" },  
{ mandarin: "手机", pinyin: "shǒujī", spanish: "teléfono móvil" },  
{ mandarin: "汽车", pinyin: "qìchē", spanish: "automóvil" },  
{ mandarin: "飞机", pinyin: "fēijī", spanish: "avión" },  
{ mandarin: "火车", pinyin: "huǒchē", spanish: "tren" },  
{ mandarin: "学习", pinyin: "xuéxí", spanish: "estudiar" },  
{ mandarin: "考试", pinyin: "kǎoshì", spanish: "examen" },  
{ mandarin: "教师", pinyin: "jiàoshī", spanish: "profesor" },  
{ mandarin: "学生", pinyin: "xuéshēng", spanish: "estudiante" },  
{ mandarin: "医院", pinyin: "yīyuàn", spanish: "hospital" },  
{ mandarin: "医生", pinyin: "yīshēng", spanish: "médico" },  
{ mandarin: "健康", pinyin: "jiànkāng", spanish: "salud" },  
{ mandarin: "食物", pinyin: "shíwù", spanish: "comida" },  
{ mandarin: "水果", pinyin: "shuǐguǒ", spanish: "fruta" },  
{ mandarin: "蔬菜", pinyin: "shūcài", spanish: "verdura" },  
{ mandarin: "饮料", pinyin: "yǐnliào", spanish: "bebida" },  
{ mandarin: "衣服", pinyin: "yīfu", spanish: "ropa" },  
{ mandarin: "鞋子", pinyin: "xiézi", spanish: "zapatos" },  
{ mandarin: "帽子", pinyin: "màozi", spanish: "sombrero" },  
{ mandarin: "颜色", pinyin: "yánsè", spanish: "color" },  
{ mandarin: "红色", pinyin: "hóngsè", spanish: "rojo" },  
{ mandarin: "蓝色", pinyin: "lánsè", spanish: "azul" },  
{ mandarin: "绿色", pinyin: "lǜsè", spanish: "verde" },  
{ mandarin: "白色", pinyin: "báisè", spanish: "blanco" },  
{ mandarin: "黑色", pinyin: "hēisè", spanish: "negro" },  
{ mandarin: "动物", pinyin: "dòngwù", spanish: "animal" },  
{ mandarin: "狗", pinyin: "gǒu", spanish: "perro" },  
{ mandarin: "猫", pinyin: "māo", spanish: "gato" },  
{ mandarin: "鸟", pinyin: "niǎo", spanish: "pájaro" },  
{ mandarin: "鱼", pinyin: "yú", spanish: "pez" },  
{ mandarin: "树", pinyin: "shù", spanish: "árbol" },  
{ mandarin: "花", pinyin: "huā", spanish: "flor" },  
{ mandarin: "山", pinyin: "shān", spanish: "montaña" },  
{ mandarin: "河", pinyin: "hé", spanish: "río" },  
{ mandarin: "海", pinyin: "hǎi", spanish: "mar" },  
{ mandarin: "雨", pinyin: "yǔ", spanish: "lluvia" },  
{ mandarin: "雪", pinyin: "xuě", spanish: "nieve" },  
{ mandarin: "风", pinyin: "fēng", spanish: "viento" },  
{ mandarin: "电", pinyin: "diàn", spanish: "electricidad" },  
{ mandarin: "火", pinyin: "huǒ", spanish: "fuego" },  
{ mandarin: "空气", pinyin: "kōngqì", spanish: "aire" },  
{ mandarin: "地球", pinyin: "dìqiú", spanish: "planeta Tierra" },  
{ mandarin: "宇宙", pinyin: "yǔzhòu", spanish: "universo" },  
{ mandarin: "爱情", pinyin: "àiqíng", spanish: "amor romántico" },  
{ mandarin: "幸福", pinyin: "xìngfú", spanish: "felicidad" },  
{ mandarin: "快乐", pinyin: "kuàilè", spanish: "alegría" },  
{ mandarin: "悲伤", pinyin: "bēishāng", spanish: "tristeza" },  
{ mandarin: "生气", pinyin: "shēngqì", spanish: "enojo" },  
{ mandarin: "害怕", pinyin: "hàipà", spanish: "miedo" },  
{ mandarin: "惊讶", pinyin: "jīngyà", spanish: "sorpresa" },  
{ mandarin: "问题", pinyin: "wèntí", spanish: "pregunta" },  
{ mandarin: "答案", pinyin: "dá'àn", spanish: "respuesta" },  
{ mandarin: "错误", pinyin: "cuòwù", spanish: "error" },  
{ mandarin: "正确", pinyin: "zhèngquè", spanish: "correcto" },  
{ mandarin: "成功", pinyin: "chénggōng", spanish: "éxito" },  
{ mandarin: "失败", pinyin: "shībài", spanish: "fracaso" },  
{ mandarin: "帮助", pinyin: "bāngzhù", spanish: "ayuda" },  
{ mandarin: "支持", pinyin: "zhīchí", spanish: "apoyo" },  
{ mandarin: "自由", pinyin: "zìyóu", spanish: "libertad" },  
{ mandarin: "和平", pinyin: "hépíng", spanish: "paz" },  
{ mandarin: "战争", pinyin: "zhànzhēng", spanish: "guerra" },  
{ mandarin: "经济", pinyin: "jīngjì", spanish: "economía" },  
{ mandarin: "政治", pinyin: "zhèngzhì", spanish: "política" },  
{ mandarin: "社会", pinyin: "shèhuì", spanish: "sociedad" },  
{ mandarin: "法律", pinyin: "fǎlǜ", spanish: "ley" },  
{ mandarin: "历史", pinyin: "lìshǐ", spanish: "historia" },  
{ mandarin: "科学", pinyin: "kēxué", spanish: "ciencia" },  
{ mandarin: "技术", pinyin: "jìshù", spanish: "tecnología" },  
{ mandarin: "艺术", pinyin: "yìshù", spanish: "arte" },  
{ mandarin: "运动", pinyin: "yùndòng", spanish: "deporte" },  
{ mandarin: "游戏", pinyin: "yóuxì", spanish: "juego" },  
{ mandarin: "旅行", pinyin: "lǚxíng", spanish: "viaje" },  
{ mandarin: "地图", pinyin: "dìtú", spanish: "mapa" },  
{ mandarin: "方向", pinyin: "fāngxiàng", spanish: "dirección" },  
{ mandarin: "左边", pinyin: "zuǒbiān", spanish: "izquierda" },  
{ mandarin: "右边", pinyin: "yòubiān", spanish: "derecha" },  
{ mandarin: "中间", pinyin: "zhōngjiān", spanish: "centro" },  
{ mandarin: "东西", pinyin: "dōngxi", spanish: "cosa" },  
{ mandarin: "价格", pinyin: "jiàgé", spanish: "precio" },  
{ mandarin: "钱", pinyin: "qián", spanish: "dinero" },  
{ mandarin: "商店", pinyin: "shāngdiàn", spanish: "tienda" },  
{ mandarin: "市场", pinyin: "shìchǎng", spanish: "mercado" },  
{ mandarin: "公司", pinyin: "gōngsī", spanish: "empresa" },  
{ mandarin: "会议", pinyin: "huìyì", spanish: "reunión" },  
{ mandarin: "新闻", pinyin: "xīnwén", spanish: "noticias" },  
{ mandarin: "网络", pinyin: "wǎngluò", spanish: "internet" },  
{ mandarin: "安全", pinyin: "ānquán", spanish: "seguridad" },  
{ mandarin: "危险", pinyin: "wēixiǎn", spanish: "peligro" },  
{ mandarin: "机会", pinyin: "jīhuì", spanish: "oportunidad" },  
{ mandarin: "梦想", pinyin: "mèngxiǎng", spanish: "sueño" },  
{ mandarin: "现实", pinyin: "xiànshí", spanish: "realidad" },  
{ mandarin: "希望", pinyin: "xīwàng", spanish: "esperanza" },  
{ mandarin: "变化", pinyin: "biànhuà", spanish: "cambio" },  
{ mandarin: "传统", pinyin: "chuántǒng", spanish: "tradición" },  
{ mandarin: "现代", pinyin: "xiàndài", spanish: "moderno" },  
{ mandarin: "原因", pinyin: "yuányīn", spanish: "razón" },  
{ mandarin: "结果", pinyin: "jiéguǒ", spanish: "resultado" },  
{ mandarin: "方法", pinyin: "fāngfǎ", spanish: "método" },  
{ mandarin: "经验", pinyin: "jīngyàn", spanish: "experiencia" },  
{ mandarin: "知识", pinyin: "zhīshi", spanish: "conocimiento" },  
{ mandarin: "能力", pinyin: "nénglì", spanish: "habilidad" },  
{ mandarin: "责任", pinyin: "zérèn", spanish: "responsabilidad" },  
{ mandarin: "决定", pinyin: "juédìng", spanish: "decisión" },  
{ mandarin: "选择", pinyin: "xuǎnzé", spanish: "elección" },  
{ mandarin: "困难", pinyin: "kùnnan", spanish: "dificultad" },  
{ mandarin: "解决", pinyin: "jiějué", spanish: "solución" },  
{ mandarin: "发现", pinyin: "fāxiàn", spanish: "descubrimiento" },  
{ mandarin: "发展", pinyin: "fāzhǎn", spanish: "desarrollo" },  
{ mandarin: "进步", pinyin: "jìnbù", spanish: "progreso" },  
{ mandarin: "未来", pinyin: "wèilái", spanish: "futuro" },  
{ mandarin: "过去", pinyin: "guòqù", spanish: "pasado" },  
{ mandarin: "现在", pinyin: "xiànzài", spanish: "presente" },  
{ mandarin: "永远", pinyin: "yǒngyuǎn", spanish: "para siempre" },  
{ mandarin: "突然", pinyin: "tūrán", spanish: "repentino" },  
{ mandarin: "当然", pinyin: "dāngrán", spanish: "por supuesto" },  
{ mandarin: "可能", pinyin: "kěnéng", spanish: "posible" },  
{ mandarin: "必须", pinyin: "bìxū", spanish: "deber" },  
{ mandarin: "一起", pinyin: "yīqǐ", spanish: "juntos" },  
{ mandarin: "个人", pinyin: "gèrén", spanish: "individual" },  
{ mandarin: "公共", pinyin: "gōnggòng", spanish: "público" },  
{ mandarin: "私人", pinyin: "sīrén", spanish: "privado" },  
{ mandarin: "重要", pinyin: "zhòngyào", spanish: "importante" },  
{ mandarin: "简单", pinyin: "jiǎndān", spanish: "sencillo" },  
{ mandarin: "复杂", pinyin: "fùzá", spanish: "complejo" },  
{ mandarin: "清楚", pinyin: "qīngchu", spanish: "claro" },  
{ mandarin: "明白", pinyin: "míngbai", spanish: "entender" },  
{ mandarin: "同意", pinyin: "tóngyì", spanish: "estar de acuerdo" },  
{ mandarin: "反对", pinyin: "fǎnduì", spanish: "oponerse" },  
{ mandarin: "接受", pinyin: "jiēshòu", spanish: "aceptar" },  
{ mandarin: "拒绝", pinyin: "jùjué", spanish: "rechazar" },  
{ mandarin: "开始", pinyin: "kāishǐ", spanish: "comenzar" },  
{ mandarin: "结束", pinyin: "jiéshù", spanish: "terminar" },  
{ mandarin: "继续", pinyin: "jìxù", spanish: "continuar" },  
{ mandarin: "停止", pinyin: "tíngzhǐ", spanish: "detener" },  
{ mandarin: "成功", pinyin: "chénggōng", spanish: "éxito" },  
{ mandarin: "失败", pinyin: "shībài", spanish: "fracaso" },  
{ mandarin: "相信", pinyin: "xiāngxìn", spanish: "creer" },  
{ mandarin: "怀疑", pinyin: "huáiyí", spanish: "dudar" },  
{ mandarin: "忘记", pinyin: "wàngjì", spanish: "olvidar" },  
{ mandarin: "记得", pinyin: "jìde", spanish: "recordar" },  
{ mandarin: "出现", pinyin: "chūxiàn", spanish: "aparecer" },  
{ mandarin: "消失", pinyin: "xiāoshī", spanish: "desaparecer" },     
{ mandarin: "好", pinyin: "hǎo", spanish: "bueno" },
{ mandarin: "号", pinyin: "hào", spanish: "número" },
{ mandarin: "喝", pinyin: "hē", spanish: "beber" },
{ mandarin: "和", pinyin: "hé", spanish: "y" },
{ mandarin: "很", pinyin: "hěn", spanish: "muy" },
{ mandarin: "后面", pinyin: "hòumiàn", spanish: "detrás" },
{ mandarin: "回", pinyin: "huí", spanish: "regresar" },
{ mandarin: "会", pinyin: "huì", spanish: "poder" },
{ mandarin: "几", pinyin: "jǐ", spanish: "cuántos/cuántas" },
{ mandarin: "家", pinyin: "jiā", spanish: "hogar" },
{ mandarin: "叫", pinyin: "jiào", spanish: "llamar" },
{ mandarin: "今天", pinyin: "jīntiān", spanish: "hoy" },
{ mandarin: "九", pinyin: "jiǔ", spanish: "nueve" },
{ mandarin: "开", pinyin: "kāi", spanish: "abrir" },
{ mandarin: "看", pinyin: "kàn", spanish: "mirar" },
{ mandarin: "看见", pinyin: "kànjiàn", spanish: "ver" },
{ mandarin: "块", pinyin: "kuài", spanish: "pedazo" },
{ mandarin: "来", pinyin: "lá", spanish: "venir" },
{ mandarin: "老师", pinyin: "lǎoshī", spanish: "profesor/profesora" },
{ mandarin: "了", pinyin: "le", spanish: "acción completada" },
{ mandarin: "冷", pinyin: "lěng", spanish: "frío" },
{ mandarin: "里", pinyin: "lǐ", spanish: "dentro" },
{ mandarin: "六", pinyin: "liù", spanish: "seis" },
{ mandarin: "吗", pinyin: "ma", spanish: "partícula interrogativa" },
{ mandarin: "妈妈", pinyin: "māma", spanish: "mamá" },
{ mandarin: "买", pinyin: "mǎi", spanish: "comprar" },
{ mandarin: "猫", pinyin: "māo", spanish: "gato" },
{ mandarin: "没关系", pinyin: "méi guānxi", spanish: "no importa" },
{ mandarin: "没有", pinyin: "méiyǒu", spanish: "no tener/haber" },
{ mandarin: "米饭", pinyin: "mǐfàn", spanish: "arroz cocido" },
{ mandarin: "名字", pinyin: "míngzi", spanish: "nombre" },
{ mandarin: "明天", pinyin: "míngtiān", spanish: "mañana" },
{ mandarin: "哪", pinyin: "nǎ", spanish: "cuál" },
{ mandarin: "哪儿", pinyin: "nǎr", spanish: "dónde" },
{ mandarin: "那", pinyin: "nà", spanish: "ese/esa" },
{ mandarin: "苦", pinyin: "kǔ", spanish: "amargo" }  


    ],
    
    obtenerAleatoria: function() {
        return this.lista[Math.floor(Math.random() * this.lista.length)];
    }
};