class Progresso {
  static guardar(progreso) {
    localStorage.setItem('progresoChino', JSON.stringify(progreso));
  }

  static cargar() {
    const datos = localStorage.getItem('progresoChino');
    return datos ? JSON.parse(datos) : {};
  }
}

class Frases {
  static lista = [
    { mandarin: "门", pinyin: "mén", spanish: "puerta" },
    { mandarin: "雪", pinyin: "xuě", spanish: "nieve" },
    { mandarin: "非", pinyin: "fēi", spanish: "no / incorrecto" },
    { mandarin: "饿", pinyin: "è", spanish: "hambriento" },
{ mandarin: "马", pinyin: "mǎ", spanish: "caballo" },
{ mandarin: "骑", pinyin: "qí", spanish: "montar" },
{ mandarin: "高", pinyin: "gāo", spanish: "alto" },
{ mandarin: "跳", pinyin: "tiào", spanish: "saltar" },
{ mandarin: "错", pinyin: "cuò", spanish: "equivocado" },
{ mandarin: "锻", pinyin: "duàn", spanish: "forjar" },
{ mandarin: "长", pinyin: "cháng / zhǎng", spanish: "largo / crecer " },
{ mandarin: "身", pinyin: "shēn", spanish: "cuerpo" },
{ mandarin: "让", pinyin: "ràng", spanish: "permitir / dejar que" },
{ mandarin: "睡", pinyin: "shuì", spanish: "dormir" },
{ mandarin: "穿", pinyin: "chuān", spanish: "vestir" },
{ mandarin: "送", pinyin: "sòng", spanish: "enviar / acompañar" },
{ mandarin: "近", pinyin: "jìn", spanish: "cerca" },
{ mandarin: "远", pinyin: "yuǎn", spanish: "lejos" },
{ mandarin: "红", pinyin: "hóng", spanish: "rojo" },
{ mandarin: "累", pinyin: "lèi", spanish: "cansado" },
{ mandarin: "黑", pinyin: "hēi", spanish: "negro" },
{ mandarin: "姐", pinyin: "jiě", spanish: "hermana mayor" },
{ mandarin: "哥", pinyin: "gē", spanish: "hermano mayor" },
{ mandarin: "丈", pinyin: "zhàng", spanish: "esposo" },
{ mandarin: "夫", pinyin: "fū", spanish: "hombre / esposo" },
{ mandarin: "妻", pinyin: "qī", spanish: "esposa" },
{ mandarin: "室", pinyin: "shì", spanish: "cuarto / habitación" },
{ mandarin: "宾", pinyin: "bīn", spanish: "invitado" },
{ mandarin: "洗", pinyin: "xǐ", spanish: "lavar" },
{ mandarin: "觉", pinyin: "jiào / jué", spanish: "sueño" },
{ mandarin: "间", pinyin: "jiān", spanish: "entre / espacio" },
{ mandarin: "旅", pinyin: "lǚ", spanish: "viajar" },
{ mandarin: "餐", pinyin: "cān", spanish: "comida" },
{ mandarin: "店", pinyin: "diàn", spanish: "tienda / local" },
{ mandarin: "鸡", pinyin: "jī", spanish: "pollo" },
{ mandarin: "羊", pinyin: "yáng", spanish: "oveja" },
{ mandarin: "猪", pinyin: "zhū", spanish: "cerdo" },
{ mandarin: "蛋", pinyin: "dàn", spanish: "huevo" },
{ mandarin: "群", pinyin: "qún", spanish: "grupo / rebaño" },
{ mandarin: "菜", pinyin: "cài", spanish: "plato / verdura" },
{ mandarin: "茶", pinyin: "chá", spanish: "té" },
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },
{ mandarin: "糖", pinyin: "táng", spanish: "azúcar / dulce" },
{ mandarin: "米", pinyin: "mǐ", spanish: "arroz" },
{ mandarin: "肉", pinyin: "ròu", spanish: "carne" },
{ mandarin: "胖", pinyin: "pàng", spanish: "gordo" },
{ mandarin: "瘦", pinyin: "shòu", spanish: "delgado" },
{ mandarin: "舒", pinyin: "shū", spanish: "cómodo" },
{ mandarin: "服", pinyin: "fú", spanish: "ropa / servir" },
{ mandarin: "药", pinyin: "yào", spanish: "medicina" },
{ mandarin: "病", pinyin: "bìng", spanish: "enfermedad / enfermo" },
{ mandarin: "医", pinyin: "yī", spanish: "médico" },
{ mandarin: "院", pinyin: "yuàn", spanish: "institución / hospital" },
{ mandarin: "疼", pinyin: "téng", spanish: "dolor" },
{ mandarin: "动", pinyin: "dòng", spanish: "mover" },
{ mandarin: "画", pinyin: "huà", spanish: "dibujar / pintura" },
{ mandarin: "爱", pinyin: "ài", spanish: "amar" },
{ mandarin: "唱", pinyin: "chàng", spanish: "cantar" },
{ mandarin: "歌", pinyin: "gē", spanish: "canción" },
{ mandarin: "起", pinyin: "qǐ", spanish: "levantarse / comenzar" },
{ mandarin: "床", pinyin: "chuáng", spanish: "cama" },
{ mandarin: "路", pinyin: "lù", spanish: "camino / calle" },
{ mandarin: "公", pinyin: "gōng", spanish: "público / masculino" },
{ mandarin: "共", pinyin: "gòng", spanish: "compartido / común" },
{ mandarin: "汽", pinyin: "qì", spanish: "vapor / gas" },
{ mandarin: "车", pinyin: "chē", spanish: "vehículo" },
{ mandarin: "站", pinyin: "zhàn", spanish: "estación / parar" },
{ mandarin: "场", pinyin: "chǎng", spanish: "campo / lugar" },
{ mandarin: "票", pinyin: "piào", spanish: "boleto / entrada" },
{ mandarin: "晚", pinyin: "wǎn", spanish: "tarde / noche" },
{ mandarin: "昨", pinyin: "zuó", spanish: "ayer" },
{ mandarin: "玩", pinyin: "wán", spanish: "jugar" },
{ mandarin: "便", pinyin: "pián / biàn", spanish: "conveniente / barato" },
{ mandarin: "宜", pinyin: "yí", spanish: "adecuado" },
{ mandarin: "慢", pinyin: "màn", spanish: "lento" },
{ mandarin: "题", pinyin: "tí", spanish: "pregunta / tema" },
{ mandarin: "问", pinyin: "wèn", spanish: "preguntar" },
{ mandarin: "复", pinyin: "fù", spanish: "repetir" },
{ mandarin: "习", pinyin: "xí", spanish: "practicar / hábito" },
{ mandarin: "新", pinyin: "xīn", spanish: "nuevo" },
{ mandarin: "容", pinyin: "róng", spanish: "contenido / fácil" },
{ mandarin: "易", pinyin: "yì", spanish: "fácil" },
{ mandarin: "始", pinyin: "shǐ", spanish: "comenzar" },
{ mandarin: "练", pinyin: "liàn", spanish: "practicar / entrenar" },
{ mandarin: "准", pinyin: "zhǔn", spanish: "exacto / preparar" },
{ mandarin: "备", pinyin: "bèi", spanish: "preparar" },
{ mandarin: "欢", pinyin: "huān", spanish: "feliz" },
{ mandarin: "迎", pinyin: "yíng", spanish: "dar la bienvenida" },
{ mandarin: "意", pinyin: "yì", spanish: "idea / significado" },
{ mandarin: "思", pinyin: "sī", spanish: "pensar" },
{ mandarin: "希", pinyin: "xī", spanish: "esperanza" },
{ mandarin: "望", pinyin: "wàng", spanish: "esperar / desear" },
{ mandarin: "晴", pinyin: "qíng", spanish: "despejado" },
{ mandarin: "阴", pinyin: "yīn", spanish: "nublado" },
{ mandarin: "度", pinyin: "dù", spanish: "grad" },
{ mandarin: "零", pinyin: "líng", spanish: "cero" },
{ mandarin: "务", pinyin: "wù", spanish: "servicio" },
{ mandarin: "员", pinyin: "yuán", spanish: "empleado / miembro" },
{ mandarin: "找", pinyin: "zhǎo", spanish: "buscar" },
{ mandarin: "帮", pinyin: "bāng", spanish: "ayudar" },
{ mandarin: "忙", pinyin: "máng", spanish: "ocupado / ayuda" },
{ mandarin: "旁", pinyin: "páng", spanish: "al lado de" },
{ mandarin: "边", pinyin: "biān", spanish: "lado / borde" },
{ mandarin: "左", pinyin: "zuǒ", spanish: "izquierda" },
{ mandarin: "右", pinyin: "yòu", spanish: "derecha" },
{ mandarin: "司", pinyin: "sī", spanish: "administrar" },
{ mandarin: "工", pinyin: "gōng", spanish: "trabajo / obrero" },
{ mandarin: "次", pinyin: "cì", spanish: "vez" },
{ mandarin: "然", pinyin: "rán", spanish: "así / correcto" },
{ mandarin: "后", pinyin: "hòu", spanish: "después" },
{ mandarin: "正", pinyin: "zhèng", spanish: "justo / estar" },
{ mandarin: "虽", pinyin: "suī", spanish: "aunque" },
{ mandarin: "但", pinyin: "dàn", spanish: "pero" },
{ mandarin: "因", pinyin: "yīn", spanish: "por" },
{ mandarin: "所", pinyin: "suǒ", spanish: "lugar / por eso" },
{ mandarin: "以", pinyin: "yǐ", spanish: "usar / por eso" },
{ mandarin: "已", pinyin: "yǐ", spanish: "ya" },
    { mandarin: "经", pinyin: "jīng", spanish: "pasar / ya " },
    { mandarin: "饿", pinyin: "è", spanish: "hambriento" },
{ mandarin: "马", pinyin: "mǎ", spanish: "caballo" },
{ mandarin: "骑", pinyin: "qí", spanish: "montar" },
{ mandarin: "高", pinyin: "gāo", spanish: "alto" },
{ mandarin: "跳", pinyin: "tiào", spanish: "saltar" },
{ mandarin: "错", pinyin: "cuò", spanish: "equivocado" },
{ mandarin: "锻", pinyin: "duàn", spanish: "forjar" },
{ mandarin: "长", pinyin: "cháng / zhǎng", spanish: "largo / crecer (depende del uso)" },
{ mandarin: "身", pinyin: "shēn", spanish: "cuerpo" },
{ mandarin: "让", pinyin: "ràng", spanish: "permitir / dejar que" },
{ mandarin: "睡", pinyin: "shuì", spanish: "dormir" },
{ mandarin: "穿", pinyin: "chuān", spanish: "vestir / ponerse" },
{ mandarin: "送", pinyin: "sòng", spanish: "enviar / acompañar" },
{ mandarin: "近", pinyin: "jìn", spanish: "cerca" },
{ mandarin: "远", pinyin: "yuǎn", spanish: "lejos" },
{ mandarin: "红", pinyin: "hóng", spanish: "rojo" },
{ mandarin: "累", pinyin: "lèi", spanish: "cansado" },
{ mandarin: "黑", pinyin: "hēi", spanish: "negro" },
{ mandarin: "姐", pinyin: "jiě", spanish: "hermana mayor" },
{ mandarin: "哥", pinyin: "gē", spanish: "hermano mayor" },
{ mandarin: "丈", pinyin: "zhàng", spanish: "esposo" },
{ mandarin: "夫", pinyin: "fū", spanish: "hombre / esposo" },
{ mandarin: "妻", pinyin: "qī", spanish: "esposa" },
{ mandarin: "室", pinyin: "shì", spanish: "cuarto / habitación" },
{ mandarin: "宾", pinyin: "bīn", spanish: "invitado" },
{ mandarin: "洗", pinyin: "xǐ", spanish: "lavar" },
{ mandarin: "觉", pinyin: "jiào / jué", spanish: "darse cuenta" },
{ mandarin: "间", pinyin: "jiān", spanish: "entre / espacio" },
{ mandarin: "旅", pinyin: "lǚ", spanish: "viajar" },
{ mandarin: "餐", pinyin: "cān", spanish: "comida" },
{ mandarin: "店", pinyin: "diàn", spanish: "tienda / local" },
{ mandarin: "鸡", pinyin: "jī", spanish: "pollo" },
{ mandarin: "羊", pinyin: "yáng", spanish: "oveja" },
{ mandarin: "猪", pinyin: "zhū", spanish: "cerdo" },
{ mandarin: "蛋", pinyin: "dàn", spanish: "huevo" },
{ mandarin: "群", pinyin: "qún", spanish: "grupo / rebaño" },
{ mandarin: "菜", pinyin: "cài", spanish: "plato / verdura" },
{ mandarin: "茶", pinyin: "chá", spanish: "té" },
{ mandarin: "甜", pinyin: "tián", spanish: "dulce" },
{ mandarin: "糖", pinyin: "táng", spanish: "azúcar / dulce" },
{ mandarin: "米", pinyin: "mǐ", spanish: "arroz" },
{ mandarin: "肉", pinyin: "ròu", spanish: "carne" },
{ mandarin: "胖", pinyin: "pàng", spanish: "gordo" },
{ mandarin: "瘦", pinyin: "shòu", spanish: "delgado" },
{ mandarin: "舒", pinyin: "shū", spanish: "cómodo" },
{ mandarin: "服", pinyin: "fú", spanish: "ropa / servir" },
{ mandarin: "药", pinyin: "yào", spanish: "medicina" },
{ mandarin: "病", pinyin: "bìng", spanish: "enfermedad / enfermo" },
{ mandarin: "医", pinyin: "yī", spanish: "médico" },
{ mandarin: "院", pinyin: "yuàn", spanish: "institución / hospital" },
{ mandarin: "疼", pinyin: "téng", spanish: "dolor" },
{ mandarin: "动", pinyin: "dòng", spanish: "mover" },
{ mandarin: "画", pinyin: "huà", spanish: "dibujar / pintura" },
{ mandarin: "爱", pinyin: "ài", spanish: "amar" },
{ mandarin: "唱", pinyin: "chàng", spanish: "cantar" },
{ mandarin: "歌", pinyin: "gē", spanish: "canción" },
{ mandarin: "起", pinyin: "qǐ", spanish: "levantarse / comenzar" },
{ mandarin: "床", pinyin: "chuáng", spanish: "cama" },
{ mandarin: "路", pinyin: "lù", spanish: "camino / calle" },
{ mandarin: "公", pinyin: "gōng", spanish: "público / masculino" },
{ mandarin: "共", pinyin: "gòng", spanish: "compartido / común" },
{ mandarin: "汽", pinyin: "qì", spanish: "vapor / gas" },
{ mandarin: "车", pinyin: "chē", spanish: "vehículo" },
{ mandarin: "站", pinyin: "zhàn", spanish: "estación / parar" },
{ mandarin: "场", pinyin: "chǎng", spanish: "campo / lugar" },
{ mandarin: "票", pinyin: "piào", spanish: "boleto / entrada" },
{ mandarin: "晚", pinyin: "wǎn", spanish: "tarde / noche" },
{ mandarin: "昨", pinyin: "zuó", spanish: "ayer" },
{ mandarin: "玩", pinyin: "wán", spanish: "jugar" },
{ mandarin: "便", pinyin: "pián / biàn", spanish: "conveniente / barato" },
{ mandarin: "宜", pinyin: "yí", spanish: "adecuado" },
{ mandarin: "慢", pinyin: "màn", spanish: "lento" },
{ mandarin: "题", pinyin: "tí", spanish: "pregunta / tema" },
{ mandarin: "问", pinyin: "wèn", spanish: "preguntar" },
{ mandarin: "复", pinyin: "fù", spanish: "repetir" },
{ mandarin: "习", pinyin: "xí", spanish: "practicar / hábito" },
{ mandarin: "新", pinyin: "xīn", spanish: "nuevo" },
{ mandarin: "容", pinyin: "róng", spanish: "contenido / fácil" },
{ mandarin: "易", pinyin: "yì", spanish: "fácil" },
{ mandarin: "始", pinyin: "shǐ", spanish: "comenzar" },
{ mandarin: "练", pinyin: "liàn", spanish: "practicar / entrenar" },
{ mandarin: "准", pinyin: "zhǔn", spanish: "exacto" },
{ mandarin: "备", pinyin: "bèi", spanish: "preparar" },
{ mandarin: "欢", pinyin: "huān", spanish: "feliz" },
{ mandarin: "迎", pinyin: "yíng", spanish: "dar la bienvenida" },
{ mandarin: "意", pinyin: "yì", spanish: "idea / significado" },
{ mandarin: "思", pinyin: "sī", spanish: "pensar" },
{ mandarin: "希", pinyin: "xī", spanish: "esperanza" },
{ mandarin: "望", pinyin: "wàng", spanish: "esperar / desear" },
{ mandarin: "晴", pinyin: "qíng", spanish: "despejado (clima)" },
{ mandarin: "阴", pinyin: "yīn", spanish: "nublado" },
{ mandarin: "度", pinyin: "dù", spanish: "grado" },
{ mandarin: "零", pinyin: "líng", spanish: "cero" },
{ mandarin: "务", pinyin: "wù", spanish: "servicio" },
{ mandarin: "员", pinyin: "yuán", spanish: "empleado / miembro" },
{ mandarin: "找", pinyin: "zhǎo", spanish: "buscar" },
{ mandarin: "帮", pinyin: "bāng", spanish: "ayudar" },
{ mandarin: "忙", pinyin: "máng", spanish: "ocupado" },
{ mandarin: "旁", pinyin: "páng", spanish: "al lado de" },
{ mandarin: "边", pinyin: "biān", spanish: "lado / borde" },
{ mandarin: "左", pinyin: "zuǒ", spanish: "izquierda" },
{ mandarin: "右", pinyin: "yòu", spanish: "derecha" },
{ mandarin: "司", pinyin: "sī", spanish: "administrar" },
{ mandarin: "工", pinyin: "gōng", spanish: "trabajo / obrero" },
{ mandarin: "次", pinyin: "cì", spanish: "vez" },
{ mandarin: "然", pinyin: "rán", spanish: "así / correcto" },
{ mandarin: "后", pinyin: "hòu", spanish: "después" },
{ mandarin: "正", pinyin: "zhèng", spanish: "justo / estar" },
{ mandarin: "虽", pinyin: "suī", spanish: "aunque" },
{ mandarin: "但", pinyin: "dàn", spanish: "pero" },
{ mandarin: "因", pinyin: "yīn", spanish: "por" },
{ mandarin: "所", pinyin: "suǒ", spanish: "lugar" },
{ mandarin: "以", pinyin: "yǐ", spanish: "usar" },
{ mandarin: "已", pinyin: "yǐ", spanish: "ya" }
  ];

  static obtenerAleatoria() {
    const progreso = Progresso.cargar();
    const frasesDisponibles = this.lista.filter(frase => 
      (progreso[frase.mandarin] || 0) < 5
    );
    
    if (frasesDisponibles.length === 0) {
      alert('¡Felicidades mi vida, dominaste todo! 💖');
      return this.lista[0];
    }

    
    return frasesDisponibles[Math.floor(Math.random() * frasesDisponibles.length)];
  }
}