class Progresso {
  static guardar(progreso) {
    localStorage.setItem('progresoChino', JSON.stringify(progreso));
  }

  static cargar() {
    const datos = localStorage.getItem('progresoChino');
    return datos ? JSON.parse(datos) : {};
  }
}

class Frases {
  static lista = [
    
  { mandarin: "啊", pinyin: "ā", spanish: "interjección" },
  { mandarin: "矮", pinyin: "ǎi", spanish: "bajo (estatura)" },
  { mandarin: "爱", pinyin: "ài", spanish: "amar" },
  { mandarin: "安", pinyin: "ān", spanish: "seguro/tranquilo" },
  { mandarin: "岸", pinyin: "àn", spanish: "orilla" },
  { mandarin: "暗", pinyin: "àn", spanish: "oscuro" },
  { mandarin: "把", pinyin: "bǎ", spanish: "sostener/partícula de objeto" },
  { mandarin: "百", pinyin: "bǎi", spanish: "cien" },
  { mandarin: "班", pinyin: "bān", spanish: "clase/turno" },
  { mandarin: "搬", pinyin: "bān", spanish: "mover" },
  { mandarin: "办", pinyin: "bàn", spanish: "hacer" },
  { mandarin: "半", pinyin: "bàn", spanish: "mitad" },
  { mandarin: "帮", pinyin: "bāng", spanish: "ayudar" },
  { mandarin: "包", pinyin: "bāo", spanish: "paquete" },
  { mandarin: "饱", pinyin: "bǎo", spanish: "lleno (de comida)" },
  { mandarin: "北", pinyin: "běi", spanish: "norte" },
  { mandarin: "被", pinyin: "bèi", spanish: "por (partícula pasiva)" },
  { mandarin: "本", pinyin: "běn", spanish: "raíz/origen" },
  { mandarin: "比", pinyin: "bǐ", spanish: "comparar" },
  { mandarin: "必", pinyin: "bì", spanish: "necesario" },
  { mandarin: "便", pinyin: "biàn", spanish: "conveniente" },
  { mandarin: "变", pinyin: "biàn", spanish: "cambiar" },
  { mandarin: "表", pinyin: "biǎo", spanish: "mostrar/reloj" },
  { mandarin: "别", pinyin: "bié", spanish: "no hacer algo" },
  { mandarin: "病", pinyin: "bìng", spanish: "enfermedad" },
  { mandarin: "步", pinyin: "bù", spanish: "paso" },
  { mandarin: "才", pinyin: "cái", spanish: "recién/sólo entonces" },
  { mandarin: "菜", pinyin: "cài", spanish: "plato de comida/verdura" },
  { mandarin: "参", pinyin: "cān", spanish: "participar" },
  { mandarin: "草", pinyin: "cǎo", spanish: "hierba" },
  { mandarin: "层", pinyin: "céng", spanish: "capa/piso" },
  { mandarin: "差", pinyin: "chà", spanish: "diferente/faltar" },
  { mandarin: "常", pinyin: "cháng", spanish: "a menudo" },
  { mandarin: "长", pinyin: "cháng", spanish: "largo" },
  { mandarin: "长", pinyin: "zhǎng", spanish: "crecer/jefe" },
  { mandarin: "场", pinyin: "chǎng", spanish: "lugar" },
  { mandarin: "唱", pinyin: "chàng", spanish: "cantar" },
  { mandarin: "朝", pinyin: "cháo", spanish: "hacia" },
  { mandarin: "车", pinyin: "chē", spanish: "vehículo" },
  { mandarin: "衬", pinyin: "chèn", spanish: "forro" },
  { mandarin: "城", pinyin: "chéng", spanish: "ciudad" },
  { mandarin: "成", pinyin: "chéng", spanish: "convertirse" },
  { mandarin: "吃", pinyin: "chī", spanish: "comer" },
  { mandarin: "迟", pinyin: "chí", spanish: "tarde" },
  { mandarin: "船", pinyin: "chuán", spanish: "barco" },
  { mandarin: "穿", pinyin: "chuān", spanish: "vestir" },
  { mandarin: "窗", pinyin: "chuāng", spanish: "ventana" },
  { mandarin: "春", pinyin: "chūn", spanish: "primavera" },
  { mandarin: "词", pinyin: "cí", spanish: "palabra" },
  { mandarin: "聪", pinyin: "cōng", spanish: "agudo del oído" },
  { mandarin: "从", pinyin: "cóng", spanish: "desde" },
  { mandarin: "打", pinyin: "dǎ", spanish: "golpear" },
  { mandarin: "带", pinyin: "dài", spanish: "llevar" },
  { mandarin: "待", pinyin: "dài", spanish: "esperar" },
  { mandarin: "但", pinyin: "dàn", spanish: "pero" },
  { mandarin: "蛋", pinyin: "dàn", spanish: "huevo" },
  { mandarin: "当", pinyin: "dāng", spanish: "cuando" },
  { mandarin: "刀", pinyin: "dāo", spanish: "cuchillo" },
  { mandarin: "导", pinyin: "dǎo", spanish: "guiar" },
  { mandarin: "到", pinyin: "dào", spanish: "llegar" },
  { mandarin: "道", pinyin: "dào", spanish: "camino" },
  { mandarin: "得", pinyin: "dé", spanish: "obtener" },
  { mandarin: "地", pinyin: "de", spanish: "partícula adverbial" },
  { mandarin: "灯", pinyin: "dēng", spanish: "lámpara" },
  { mandarin: "等", pinyin: "děng", spanish: "esperar" },
  { mandarin: "低", pinyin: "dī", spanish: "bajo" },
  { mandarin: "弟", pinyin: "dì", spanish: "hermano menor" },
  { mandarin: "第", pinyin: "dì", spanish: "prefijo ordinal" },
  { mandarin: "典", pinyin: "diǎn", spanish: "diccionario" },
  { mandarin: "点", pinyin: "diǎn", spanish: "punto" },
  { mandarin: "电", pinyin: "diàn", spanish: "electricidad" },
  { mandarin: "店", pinyin: "diàn", spanish: "tienda" },
  { mandarin: "掉", pinyin: "diào", spanish: "caer" },
  { mandarin: "定", pinyin: "dìng", spanish: "fijar" },
  { mandarin: "东", pinyin: "dōng", spanish: "este" },
  { mandarin: "冬", pinyin: "dōng", spanish: "invierno" },
  { mandarin: "动", pinyin: "dòng", spanish: "mover" },
  { mandarin: "都", pinyin: "dōu", spanish: "todo" },
  { mandarin: "读", pinyin: "dú", spanish: "leer" },
  { mandarin: "短", pinyin: "duǎn", spanish: "corto" },
  { mandarin: "段", pinyin: "duàn", spanish: "sección" },
  { mandarin: "锻", pinyin: "duàn", spanish: "forjar" },
  { mandarin: "对", pinyin: "duì", spanish: "correcto" },
  { mandarin: "朵", pinyin: "duǒ", spanish: "flor (clasificador)" },
  { mandarin: "饿", pinyin: "è", spanish: "hambriento" },
  { mandarin: "而", pinyin: "ér", spanish: "y (contraste)" },
  { mandarin: "耳", pinyin: "ěr", spanish: "oreja" },
  { mandarin: "发", pinyin: "fā", spanish: "enviar" },
  { mandarin: "法", pinyin: "fǎ", spanish: "ley" },
  { mandarin: "反", pinyin: "fǎn", spanish: "contrario" },
  { mandarin: "饭", pinyin: "fàn", spanish: "comida" },
  { mandarin: "方", pinyin: "fāng", spanish: "dirección" },
  { mandarin: "放", pinyin: "fàng", spanish: "poner" },
  { mandarin: "飞", pinyin: "fēi", spanish: "volar" },
  { mandarin: "分", pinyin: "fēn", spanish: "minuto" },
  { mandarin: "夫", pinyin: "fū", spanish: "marido" },
  { mandarin: "服", pinyin: "fú", spanish: "ropa" },
  { mandarin: "父", pinyin: "fù", spanish: "padre" },
  { mandarin: "复", pinyin: "fù", spanish: "repetir" },
  { mandarin: "该", pinyin: "gāi", spanish: "deber" },
  { mandarin: "改", pinyin: "gǎi", spanish: "cambiar" },
  { mandarin: "干", pinyin: "gān", spanish: "seco" },
  { mandarin: "高", pinyin: "gāo", spanish: "alto" },
  { mandarin: "告", pinyin: "gào", spanish: "decir" },
  { mandarin: "哥", pinyin: "gē", spanish: "hermano mayor" },
  { mandarin: "歌", pinyin: "gē", spanish: "canción" },
  { mandarin: "个", pinyin: "gè", spanish: "clasificador" },
  { mandarin: "给", pinyin: "gěi", spanish: "dar" },
  { mandarin: "跟", pinyin: "gēn", spanish: "con" },
  { mandarin: "更", pinyin: "gèng", spanish: "más" },
  { mandarin: "公", pinyin: "gōng", spanish: "público" },
  { mandarin: "共", pinyin: "gòng", spanish: "común" },
  { mandarin: "狗", pinyin: "gǒu", spanish: "perro" },
  { mandarin: "故", pinyin: "gù", spanish: "razón" },
  { mandarin: "顾", pinyin: "gù", spanish: "cuidar" },
  { mandarin: "刮", pinyin: "guā", spanish: "raspar" },
  { mandarin: "关", pinyin: "guān", spanish: "cerrar" },
  { mandarin: "光", pinyin: "guāng", spanish: "luz" },
  { mandarin: "广", pinyin: "guǎng", spanish: "ancho" },
  { mandarin: "贵", pinyin: "guì", spanish: "caro" },
  { mandarin: "国", pinyin: "guó", spanish: "país" },
  { mandarin: "过", pinyin: "guò", spanish: "pasar" },
  { mandarin: "孩", pinyin: "hái", spanish: "niño" },
  { mandarin: "海", pinyin: "hǎi", spanish: "mar" },
  { mandarin: "害", pinyin: "hài", spanish: "dañar" },
  { mandarin: "喊", pinyin: "hǎn", spanish: "gritar" },
  { mandarin: "汗", pinyin: "hàn", spanish: "sudor" },
  { mandarin: "行", pinyin: "háng", spanish: "fila" },
  { mandarin: "好", pinyin: "hǎo", spanish: "bueno" },
  { mandarin: "号", pinyin: "hào", spanish: "número" },
  { mandarin: "喝", pinyin: "hē", spanish: "beber" },
  { mandarin: "合", pinyin: "hé", spanish: "juntar" },
  { mandarin: "和", pinyin: "hé", spanish: "y" },
  { mandarin: "黑", pinyin: "hēi", spanish: "negro" },
  { mandarin: "红", pinyin: "hóng", spanish: "rojo" },
  { mandarin: "后", pinyin: "hòu", spanish: "después" },
  { mandarin: "候", pinyin: "hòu", spanish: "esperar" },
  { mandarin: "护", pinyin: "hù", spanish: "proteger" },
  { mandarin: "花", pinyin: "huā", spanish: "flor" },
  { mandarin: "画", pinyin: "huà", spanish: "dibujar" },
  { mandarin: "话", pinyin: "huà", spanish: "palabras" },
  { mandarin: "坏", pinyin: "huài", spanish: "malo" },
  { mandarin: "欢", pinyin: "huān", spanish: "alegre" },
  { mandarin: "还", pinyin: "huán", spanish: "devolver" },
  { mandarin: "环", pinyin: "huán", spanish: "anillo" },
  { mandarin: "换", pinyin: "huàn", spanish: "cambiar" },
  { mandarin: "黄", pinyin: "huáng", spanish: "amarillo" },
  { mandarin: "回", pinyin: "huí", spanish: "volver" },
  { mandarin: "会", pinyin: "huì", spanish: "poder" },
  { mandarin: "活", pinyin: "huó", spanish: "vivir" },
  { mandarin: "火", pinyin: "huǒ", spanish: "fuego" },
  { mandarin: "机", pinyin: "jī", spanish: "máquina" },
  { mandarin: "鸡", pinyin: "jī", spanish: "pollo" },
  { mandarin: "极", pinyin: "jí", spanish: "extremo" },
  { mandarin: "急", pinyin: "jí", spanish: "urgente" },
  { mandarin: "计", pinyin: "jì", spanish: "contar" },
  { mandarin: "记", pinyin: "jì", spanish: "recordar" },
  { mandarin: "纪", pinyin: "jì", spanish: "registrar" },
  { mandarin: "家", pinyin: "jiā", spanish: "casa" },
  { mandarin: "假", pinyin: "jiǎ", spanish: "falso" },
  { mandarin: "间", pinyin: "jiān", spanish: "entre" },
  { mandarin: "见", pinyin: "jiàn", spanish: "ver" },
  { mandarin: "健", pinyin: "jiàn", spanish: "salud" },
  { mandarin: "江", pinyin: "jiāng", spanish: "río" },
  { mandarin: "讲", pinyin: "jiǎng", spanish: "hablar" },
  { mandarin: "角", pinyin: "jiǎo", spanish: "esquina" },
  { mandarin: "脚", pinyin: "jiǎo", spanish: "pie" },
  { mandarin: "教", pinyin: "jiāo", spanish: "enseñar" },
  { mandarin: "接", pinyin: "jiē", spanish: "recibir" },
  { mandarin: "街", pinyin: "jiē", spanish: "calle" },
  { mandarin: "节", pinyin: "jié", spanish: "festividad" },
  { mandarin: "结", pinyin: "jié", spanish: "atar" },
  { mandarin: "姐", pinyin: "jiě", spanish: "hermana mayor" },
  { mandarin: "解", pinyin: "jiě", spanish: "desatar" },
  { mandarin: "借", pinyin: "jiè", spanish: "pedir prestado" },
  { mandarin: "今", pinyin: "jīn", spanish: "ahora" },
  { mandarin: "斤", pinyin: "jīn", spanish: "medio kilo" },
  { mandarin: "紧", pinyin: "jǐn", spanish: "apretado" },
  { mandarin: "进", pinyin: "jìn", spanish: "entrar" },
  { mandarin: "近", pinyin: "jìn", spanish: "cercano" },
  { mandarin: "睛", pinyin: "jīng", spanish: "ojo" },
  { mandarin: "经", pinyin: "jīng", spanish: "pasar por" },
  { mandarin: "景", pinyin: "jǐng", spanish: "paisaje" },
  { mandarin: "净", pinyin: "jìng", spanish: "limpio" },
  { mandarin: "究", pinyin: "jiū", spanish: "investigar" },
  { mandarin: "久", pinyin: "jiǔ", spanish: "largo tiempo" },
  { mandarin: "酒", pinyin: "jiǔ", spanish: "alcohol" },
  { mandarin: "旧", pinyin: "jiù", spanish: "viejo" },
  { mandarin: "就", pinyin: "jiù", spanish: "entonces" },
  { mandarin: "居", pinyin: "jū", spanish: "residir" },
  { mandarin: "句", pinyin: "jù", spanish: "oración" },
  { mandarin: "决", pinyin: "jué", spanish: "decidir" },
  { mandarin: "觉", pinyin: "jué", spanish: "sentir" },
  { mandarin: "开", pinyin: "kāi", spanish: "abrir" },
  { mandarin: "看", pinyin: "kàn", spanish: "mirar" },
  { mandarin: "考", pinyin: "kǎo", spanish: "examinar" },
  { mandarin: "渴", pinyin: "kě", spanish: "sediento" },
  { mandarin: "可", pinyin: "kě", spanish: "poder" },
  { mandarin: "刻", pinyin: "kè", spanish: "grabar" },
  { mandarin: "客", pinyin: "kè", spanish: "invitado" },
  { mandarin: "课", pinyin: "kè", spanish: "lección" },
  { mandarin: "空", pinyin: "kōng", spanish: "vacío" },
  { mandarin: "口", pinyin: "kǒu", spanish: "boca" },
  { mandarin: "哭", pinyin: "kū", spanish: "llorar" },
  { mandarin: "快", pinyin: "kuài", spanish: "rápido" },
  { mandarin: "块", pinyin: "kuài", spanish: "pedazo" },
  { mandarin: "筷", pinyin: "kuài", spanish: "palillos" },
  { mandarin: "蓝", pinyin: "lán", spanish: "azul" },
  { mandarin: "篮", pinyin: "lán", spanish: "canasta" },
  { mandarin: "老", pinyin: "lǎo", spanish: "viejo" },
  { mandarin: "乐", pinyin: "lè", spanish: "alegre" },
  { mandarin: "累", pinyin: "lèi", spanish: "cansado" },
  { mandarin: "冷", pinyin: "lěng", spanish: "frío" },
  { mandarin: "离", pinyin: "lí", spanish: "separar" },
  { mandarin: "礼", pinyin: "lǐ", spanish: "cortesía" },
  { mandarin: "里", pinyin: "lǐ", spanish: "dentro" },
  { mandarin: "理", pinyin: "lǐ", spanish: "razón" },
  { mandarin: "力", pinyin: "lì", spanish: "fuerza" },
  { mandarin: "历", pinyin: "lì", spanish: "calendario" },
  { mandarin: "利", pinyin: "lì", spanish: "beneficio" },
  { mandarin: "例", pinyin: "lì", spanish: "ejemplo" },
  { mandarin: "脸", pinyin: "liǎn", spanish: "cara" },
  { mandarin: "练", pinyin: "liàn", spanish: "practicar" },
  { mandarin: "凉", pinyin: "liáng", spanish: "fresco" },
  { mandarin: "两", pinyin: "liǎng", spanish: "dos" },
  { mandarin: "辆", pinyin: "liàng", spanish: "clasificador de vehículos" },
  { mandarin: "亮", pinyin: "liàng", spanish: "brillante" },
  { mandarin: "了", pinyin: "le", spanish: "partícula aspectual" },
  { mandarin: "料", pinyin: "liào", spanish: "material" },
  { mandarin: "邻", pinyin: "lín", spanish: "vecino" },
  { mandarin: "零", pinyin: "líng", spanish: "cero" },
  { mandarin: "领", pinyin: "lǐng", spanish: "cuello" },
  { mandarin: "流", pinyin: "liú", spanish: "fluir" },
  { mandarin: "留", pinyin: "liú", spanish: "quedarse" },
  { mandarin: "六", pinyin: "liù", spanish: "seis" },
  { mandarin: "楼", pinyin: "lóu", spanish: "edificio" },
  { mandarin: "绿", pinyin: "lǜ", spanish: "verde" },
  { mandarin: "妈", pinyin: "mā", spanish: "mamá" },
  { mandarin: "马", pinyin: "mǎ", spanish: "caballo" },
  { mandarin: "吗", pinyin: "ma", spanish: "partícula interrogativa" },
  { mandarin: "买", pinyin: "mǎi", spanish: "comprar" },
  { mandarin: "卖", pinyin: "mài", spanish: "vender" },
  { mandarin: "满", pinyin: "mǎn", spanish: "lleno" },
  { mandarin: "猫", pinyin: "māo", spanish: "gato" },
  { mandarin: "毛", pinyin: "máo", spanish: "pelo" },
  { mandarin: "帽", pinyin: "mào", spanish: "gorra" },
  { mandarin: "没", pinyin: "méi", spanish: "no tener" },
  { mandarin: "每", pinyin: "měi", spanish: "cada" },
  { mandarin: "妹", pinyin: "mèi", spanish: "hermana menor" },
  { mandarin: "门", pinyin: "mén", spanish: "puerta" },
  { mandarin: "们", pinyin: "men", spanish: "plural" },
  { mandarin: "米", pinyin: "mǐ", spanish: "arroz" },
  { mandarin: "面", pinyin: "miàn", spanish: "cara" },
  { mandarin: "民", pinyin: "mín", spanish: "pueblo" },
  { mandarin: "明", pinyin: "míng", spanish: "brillante" },
  { mandarin: "名", pinyin: "míng", spanish: "nombre" },
  { mandarin: "母", pinyin: "mǔ", spanish: "madre" },
  { mandarin: "目", pinyin: "mù", spanish: "ojo" },
  { mandarin: "拿", pinyin: "ná", spanish: "tomar" },
  { mandarin: "哪", pinyin: "nǎ", spanish: "cuál" },
  { mandarin: "那", pinyin: "nà", spanish: "ese" },
  { mandarin: "奶", pinyin: "nǎi", spanish: "leche" },
  { mandarin: "南", pinyin: "nán", spanish: "sur" },
  { mandarin: "难", pinyin: "nán", spanish: "difícil" },
  { mandarin: "脑", pinyin: "nǎo", spanish: "cerebro" },
  { mandarin: "呢", pinyin: "ne", spanish: "partícula" },
  { mandarin: "内", pinyin: "nèi", spanish: "dentro" },
  { mandarin: "能", pinyin: "néng", spanish: "poder" },
  { mandarin: "你", pinyin: "nǐ", spanish: "tú" },
  { mandarin: "年", pinyin: "nián", spanish: "año" },
  { mandarin: "念", pinyin: "niàn", spanish: "pensar" },
  { mandarin: "牛", pinyin: "niú", spanish: "vaca" },
  { mandarin: "农", pinyin: "nóng", spanish: "agricultura" },
  { mandarin: "女", pinyin: "nǚ", spanish: "mujer" },
  { mandarin: "爬", pinyin: "pá", spanish: "trepar" },
  { mandarin: "怕", pinyin: "pà", spanish: "temer" },
  { mandarin: "拍", pinyin: "pāi", spanish: "golpear" },
  { mandarin: "排", pinyin: "pái", spanish: "fila" },
  { mandarin: "派", pinyin: "pài", spanish: "enviar" },
  { mandarin: "跑", pinyin: "pǎo", spanish: "correr" },
  { mandarin: "朋", pinyin: "péng", spanish: "amigo" },
  { mandarin: "皮", pinyin: "pí", spanish: "piel" },
  { mandarin: "片", pinyin: "piàn", spanish: "rebanada" },
  { mandarin: "票", pinyin: "piào", spanish: "boleto" },
  { mandarin: "平", pinyin: "píng", spanish: "plano" },
  { mandarin: "瓶", pinyin: "píng", spanish: "botella" },
  { mandarin: "破", pinyin: "pò", spanish: "romper" },
  { mandarin: "七", pinyin: "qī", spanish: "siete" },
  { mandarin: "其", pinyin: "qí", spanish: "su" },
  { mandarin: "骑", pinyin: "qí", spanish: "montar" },
  { mandarin: "起", pinyin: "qǐ", spanish: "levantarse" },
  { mandarin: "汽", pinyin: "qì", spanish: "vapor" },
  { mandarin: "千", pinyin: "qiān", spanish: "mil" },
  { mandarin: "前", pinyin: "qián", spanish: "antes" },
  { mandarin: "钱", pinyin: "qián", spanish: "dinero" },
  { mandarin: "桥", pinyin: "qiáo", spanish: "puente" },
  { mandarin: "亲", pinyin: "qīn", spanish: "pariente" },
  { mandarin: "轻", pinyin: "qīng", spanish: "ligero" },
  { mandarin: "清", pinyin: "qīng", spanish: "claro" },
  { mandarin: "情", pinyin: "qíng", spanish: "sentimiento" },
  { mandarin: "请", pinyin: "qǐng", spanish: "invitar" },
  { mandarin: "秋", pinyin: "qiū", spanish: "otoño" },
  { mandarin: "球", pinyin: "qiú", spanish: "pelota" },
  { mandarin: "区", pinyin: "qū", spanish: "área" },
  { mandarin: "取", pinyin: "qǔ", spanish: "tomar" },
  { mandarin: "去", pinyin: "qù", spanish: "ir" },
  { mandarin: "全", pinyin: "quán", spanish: "completo" },
  { mandarin: "然", pinyin: "rán", spanish: "así" },
  { mandarin: "让", pinyin: "ràng", spanish: "dejar" },
  { mandarin: "热", pinyin: "rè", spanish: "caliente" },
  { mandarin: "人", pinyin: "rén", spanish: "persona" },
  { mandarin: "认", pinyin: "rèn", spanish: "reconocer" },
  { mandarin: "任", pinyin: "rèn", spanish: "cualquier" },
  { mandarin: "日", pinyin: "rì", spanish: "día" },
  { mandarin: "容", pinyin: "róng", spanish: "contener" },
  { mandarin: "肉", pinyin: "ròu", spanish: "carne" },
  { mandarin: "三", pinyin: "sān", spanish: "tres" },
  { mandarin: "山", pinyin: "shān", spanish: "montaña" },
  { mandarin: "伤", pinyin: "shāng", spanish: "herir" },
  { mandarin: "商", pinyin: "shāng", spanish: "negociar" },
  { mandarin: "上", pinyin: "shàng", spanish: "arriba" },
  { mandarin: "少", pinyin: "shǎo", spanish: "poco" },
  { mandarin: "绍", pinyin: "shào", spanish: "presentar" },
  { mandarin: "舍", pinyin: "shě", spanish: "dejar" },
  { mandarin: "谁", pinyin: "shéi", spanish: "quién" },
  { mandarin: "身", pinyin: "shēn", spanish: "cuerpo" },
  { mandarin: "深", pinyin: "shēn", spanish: "profundo" },
  { mandarin: "什", pinyin: "shén", spanish: "qué" },
  { mandarin: "生", pinyin: "shēng", spanish: "nacer" },
  { mandarin: "声", pinyin: "shēng", spanish: "sonido" },
  { mandarin: "省", pinyin: "shěng", spanish: "provincia" },
  { mandarin: "师", pinyin: "shī", spanish: "maestro" },
  { mandarin: "十", pinyin: "shí", spanish: "diez" },
  { mandarin: "什", pinyin: "shí", spanish: "diez (variante)" },
  { mandarin: "石", pinyin: "shí", spanish: "piedra" },
  { mandarin: "时", pinyin: "shí", spanish: "tiempo" },
  { mandarin: "识", pinyin: "shí", spanish: "conocer" },
  { mandarin: "实", pinyin: "shí", spanish: "real" },
  { mandarin: "食", pinyin: "shí", spanish: "comer" },
  { mandarin: "史", pinyin: "shǐ", spanish: "historia" },
  { mandarin: "始", pinyin: "shǐ", spanish: "comenzar" },
  { mandarin: "市", pinyin: "shì", spanish: "mercado" },
  { mandarin: "事", pinyin: "shì", spanish: "asunto" },
  { mandarin: "试", pinyin: "shì", spanish: "probar" },
  { mandarin: "室", pinyin: "shì", spanish: "habitación" },
  { mandarin: "是", pinyin: "shì", spanish: "ser" },
  { mandarin: "世", pinyin: "shì", spanish: "mundo" },
  { mandarin: "收", pinyin: "shōu", spanish: "recibir" },
  { mandarin: "手", pinyin: "shǒu", spanish: "mano" },
  { mandarin: "首", pinyin: "shǒu", spanish: "cabeza" },
  { mandarin: "受", pinyin: "shòu", spanish: "recibir" },
  { mandarin: "书", pinyin: "shū", spanish: "libro" },
  { mandarin: "叔", pinyin: "shū", spanish: "tío" },
  { mandarin: "舒", pinyin: "shū", spanish: "cómodo" },
  { mandarin: "术", pinyin: "shù", spanish: "arte" },
  { mandarin: "树", pinyin: "shù", spanish: "árbol" },
  { mandarin: "数", pinyin: "shù", spanish: "contar" },
  { mandarin: "双", pinyin: "shuāng", spanish: "par" },
  { mandarin: "水", pinyin: "shuǐ", spanish: "agua" },
  { mandarin: "睡", pinyin: "shuì", spanish: "dormir" },
  { mandarin: "说", pinyin: "shuō", spanish: "hablar" },
  { mandarin: "司", pinyin: "sī", spanish: "dirigir" },
  { mandarin: "思", pinyin: "sī", spanish: "pensar" },
  { mandarin: "死", pinyin: "sǐ", spanish: "morir" },
  { mandarin: "四", pinyin: "sì", spanish: "cuatro" },
  { mandarin: "送", pinyin: "sòng", spanish: "enviar" },
  { mandarin: "诉", pinyin: "sù", spanish: "contar" },
  { mandarin: "虽", pinyin: "suī", spanish: "aunque" },
  { mandarin: "岁", pinyin: "suì", spanish: "años de edad" },
  { mandarin: "所", pinyin: "suǒ", spanish: "lugar" },
  { mandarin: "他", pinyin: "tā", spanish: "él" },
  { mandarin: "它", pinyin: "tā", spanish: "ello" },
  { mandarin: "她", pinyin: "tā", spanish: "ella" },
  { mandarin: "台", pinyin: "tái", spanish: "plataforma" },
  { mandarin: "太", pinyin: "tài", spanish: "demasiado" },
  { mandarin: "谈", pinyin: "tán", spanish: "hablar" },
  { mandarin: "汤", pinyin: "tāng", spanish: "sopa" },
  { mandarin: "糖", pinyin: "táng", spanish: "azúcar" },
  { mandarin: "躺", pinyin: "tǎng", spanish: "recostarse" },
  { mandarin: "讨", pinyin: "tǎo", spanish: "discutir" },
  { mandarin: "特", pinyin: "tè", spanish: "especial" },
  { mandarin: "疼", pinyin: "téng", spanish: "dolor" },
  { mandarin: "踢", pinyin: "tī", spanish: "patear" },
  { mandarin: "题", pinyin: "tí", spanish: "tema" },
  { mandarin: "体", pinyin: "tǐ", spanish: "cuerpo" },
  { mandarin: "天", pinyin: "tiān", spanish: "día/cielo" },
  { mandarin: "条", pinyin: "tiáo", spanish: "raya" },
  { mandarin: "跳", pinyin: "tiào", spanish: "saltar" },
  { mandarin: "听", pinyin: "tīng", spanish: "escuchar" },
  { mandarin: "停", pinyin: "tíng", spanish: "detener" },
  { mandarin: "挺", pinyin: "tǐng", spanish: "erguido" },
  { mandarin: "通", pinyin: "tōng", spanish: "pasar" },
  { mandarin: "同", pinyin: "tóng", spanish: "igual" },
  { mandarin: "痛", pinyin: "tòng", spanish: "dolor" },
  { mandarin: "头", pinyin: "tóu", spanish: "cabeza" },
  { mandarin: "突", pinyin: "tū", spanish: "repentino" },
  { mandarin: "图", pinyin: "tú", spanish: "mapa" },
  { mandarin: "土", pinyin: "tǔ", spanish: "tierra" },
  { mandarin: "团", pinyin: "tuán", spanish: "grupo" },
  { mandarin: "推", pinyin: "tuī", spanish: "empujar" },
  { mandarin: "腿", pinyin: "tuǐ", spanish: "pierna" },
  { mandarin: "退", pinyin: "tuì", spanish: "retirarse" },
  { mandarin: "脱", pinyin: "tuō", spanish: "quitarse" },
  { mandarin: "袜", pinyin: "wà", spanish: "calcetín" },
  { mandarin: "外", pinyin: "wài", spanish: "exterior" },
  { mandarin: "完", pinyin: "wán", spanish: "terminar" },
  { mandarin: "玩", pinyin: "wán", spanish: "jugar" },
  { mandarin: "晚", pinyin: "wǎn", spanish: "tarde" },
  { mandarin: "碗", pinyin: "wǎn", spanish: "tazón" },
  { mandarin: "万", pinyin: "wàn", spanish: "diez mil" },
  { mandarin: "王", pinyin: "wáng", spanish: "rey" },
  { mandarin: "网", pinyin: "wǎng", spanish: "red" },
  { mandarin: "往", pinyin: "wǎng", spanish: "ir" },
  { mandarin: "忘", pinyin: "wàng", spanish: "olvidar" },
  { mandarin: "危", pinyin: "wēi", spanish: "peligroso" },
  { mandarin: "为", pinyin: "wèi", spanish: "por" },
  { mandarin: "围", pinyin: "wéi", spanish: "rodear" },
  { mandarin: "卫", pinyin: "wèi", spanish: "guardar" },
  { mandarin: "位", pinyin: "wèi", spanish: "posición" },
  { mandarin: "文", pinyin: "wén", spanish: "lengua" },
  { mandarin: "闻", pinyin: "wén", spanish: "oler" },
  { mandarin: "问", pinyin: "wèn", spanish: "preguntar" },
  { mandarin: "我", pinyin: "wǒ", spanish: "yo" },
  { mandarin: "握", pinyin: "wò", spanish: "agarrar" },
  { mandarin: "屋", pinyin: "wū", spanish: "casa" },
  { mandarin: "五", pinyin: "wǔ", spanish: "cinco" },
  { mandarin: "午", pinyin: "wǔ", spanish: "mediodía" },
  { mandarin: "舞", pinyin: "wǔ", spanish: "danzar" },
  { mandarin: "务", pinyin: "wù", spanish: "asunto" },
  { mandarin: "物", pinyin: "wù", spanish: "cosa" },
  { mandarin: "误", pinyin: "wù", spanish: "error" },
  { mandarin: "西", pinyin: "xī", spanish: "oeste" },
  { mandarin: "希", pinyin: "xī", spanish: "esperar" },
  { mandarin: "息", pinyin: "xī", spanish: "respirar" },
  { mandarin: "习", pinyin: "xí", spanish: "practicar" },
  { mandarin: "洗", pinyin: "xǐ", spanish: "lavar" },
  { mandarin: "喜", pinyin: "xǐ", spanish: "gustar" },
  { mandarin: "戏", pinyin: "xì", spanish: "obra" },
  { mandarin: "系", pinyin: "xì", spanish: "sistema" },
  { mandarin: "细", pinyin: "xì", spanish: "delgado" },
  { mandarin: "下", pinyin: "xià", spanish: "abajo" },
  { mandarin: "夏", pinyin: "xià", spanish: "verano" },
  { mandarin: "先", pinyin: "xiān", spanish: "primero" },
  { mandarin: "鲜", pinyin: "xiān", spanish: "fresco" },
  { mandarin: "显", pinyin: "xiǎn", spanish: "mostrar" },
  { mandarin: "现", pinyin: "xiàn", spanish: "presente" },
  { mandarin: "县", pinyin: "xiàn", spanish: "condado" },
  { mandarin: "香", pinyin: "xiāng", spanish: "fragante" },
  { mandarin: "乡", pinyin: "xiāng", spanish: "campo" },
  { mandarin: "相", pinyin: "xiāng", spanish: "mutuamente" },
  { mandarin: "想", pinyin: "xiǎng", spanish: "pensar" },
  { mandarin: "响", pinyin: "xiǎng", spanish: "sonar" },
  { mandarin: "像", pinyin: "xiàng", spanish: "parecerse" },
  { mandarin: "向", pinyin: "xiàng", spanish: "hacia" },
  { mandarin: "象", pinyin: "xiàng", spanish: "elefante" },
  { mandarin: "削", pinyin: "xiāo", spanish: "pelar" },
  { mandarin: "小", pinyin: "xiǎo", spanish: "pequeño" },
  { mandarin: "校", pinyin: "xiào", spanish: "colegio" },
  { mandarin: "笑", pinyin: "xiào", spanish: "reír" },
  { mandarin: "些", pinyin: "xiē", spanish: "algunos" },
  { mandarin: "鞋", pinyin: "xié", spanish: "zapato" },
  { mandarin: "写", pinyin: "xiě", spanish: "escribir" },
  { mandarin: "谢", pinyin: "xiè", spanish: "agradecer" },
  { mandarin: "新", pinyin: "xīn", spanish: "nuevo" },
  { mandarin: "信", pinyin: "xìn", spanish: "creer" },
  { mandarin: "兴", pinyin: "xìng", spanish: "próspero" },
  { mandarin: "星", pinyin: "xīng", spanish: "estrella" },
  { mandarin: "行", pinyin: "xíng", spanish: "hacer" },
  { mandarin: "幸", pinyin: "xìng", spanish: "afortunado" },
  { mandarin: "姓", pinyin: "xìng", spanish: "apellido" },
  { mandarin: "休", pinyin: "xiū", spanish: "descansar" },
  { mandarin: "修", pinyin: "xiū", spanish: "reparar" },
  { mandarin: "许", pinyin: "xǔ", spanish: "permitir" },
  { mandarin: "需", pinyin: "xū", spanish: "necesitar" },
  { mandarin: "选", pinyin: "xuǎn", spanish: "elegir" },
  { mandarin: "学", pinyin: "xué", spanish: "aprender" },
  { mandarin: "雪", pinyin: "xuě", spanish: "nieve" },
  { mandarin: "血", pinyin: "xuè", spanish: "sangre" },
  { mandarin: "寻", pinyin: "xún", spanish: "buscar" },
  { mandarin: "呀", pinyin: "ya", spanish: "interjección" },
  { mandarin: "研", pinyin: "yán", spanish: "investigar" },
  { mandarin: "颜", pinyin: "yán", spanish: "color" },
  { mandarin: "眼", pinyin: "yǎn", spanish: "ojo" },
  { mandarin: "演", pinyin: "yǎn", spanish: "actuar" },
  { mandarin: "羊", pinyin: "yáng", spanish: "oveja" },
  { mandarin: "阳", pinyin: "yáng", spanish: "sol" },
  { mandarin: "养", pinyin: "yǎng", spanish: "criar" },
  { mandarin: "样", pinyin: "yàng", spanish: "aspecto" },
  { mandarin: "腰", pinyin: "yāo", spanish: "cintura" },
  { mandarin: "药", pinyin: "yào", spanish: "medicina" },
  { mandarin: "要", pinyin: "yào", spanish: "querer" },
  { mandarin: "也", pinyin: "yě", spanish: "también" },
  { mandarin: "业", pinyin: "yè", spanish: "profesión" },
  { mandarin: "叶", pinyin: "yè", spanish: "hoja" },
  { mandarin: "页", pinyin: "yè", spanish: "página" },
  { mandarin: "一", pinyin: "yī", spanish: "uno" },
  { mandarin: "医", pinyin: "yī", spanish: "médico" },
  { mandarin: "衣", pinyin: "yī", spanish: "ropa" },
  { mandarin: "宜", pinyin: "yí", spanish: "apropiado" },
  { mandarin: "姨", pinyin: "yí", spanish: "tía" },
  { mandarin: "移", pinyin: "yí", spanish: "mover" },
  { mandarin: "已", pinyin: "yǐ", spanish: "ya" },
  { mandarin: "以", pinyin: "yǐ", spanish: "con" },
  { mandarin: "椅", pinyin: "yǐ", spanish: "silla" },
  { mandarin: "意", pinyin: "yì", spanish: "idea" },
  { mandarin: "义", pinyin: "yì", spanish: "significado" },
  { mandarin: "因", pinyin: "yīn", spanish: "causa" },
  { mandarin: "阴", pinyin: "yīn", spanish: "nublado" },
  { mandarin: "音", pinyin: "yīn", spanish: "sonido" },
  { mandarin: "银", pinyin: "yín", spanish: "plata" },
  { mandarin: "引", pinyin: "yǐn", spanish: "guiar" },
  { mandarin: "应", pinyin: "yīng", spanish: "deber" },
  { mandarin: "英", pinyin: "yīng", spanish: "héroe" },
  { mandarin: "迎", pinyin: "yíng", spanish: "recibir" },
  { mandarin: "影", pinyin: "yǐng", spanish: "sombra" },
  { mandarin: "用", pinyin: "yòng", spanish: "usar" },
  { mandarin: "优", pinyin: "yōu", spanish: "excelente" },
  { mandarin: "邮", pinyin: "yóu", spanish: "correo" },
  { mandarin: "游", pinyin: "yóu", spanish: "nadar" },
  { mandarin: "友", pinyin: "yǒu", spanish: "amigo" },
  { mandarin: "有", pinyin: "yǒu", spanish: "tener" },
  { mandarin: "又", pinyin: "yòu", spanish: "otra vez" },
  { mandarin: "鱼", pinyin: "yú", spanish: "pez" },
  { mandarin: "愉", pinyin: "yú", spanish: "alegre" },
  { mandarin: "雨", pinyin: "yǔ", spanish: "lluvia" },
  { mandarin: "语", pinyin: "yǔ", spanish: "idioma" },
  { mandarin: "育", pinyin: "yù", spanish: "criar" },
  { mandarin: "预", pinyin: "yù", spanish: "pre-" },
  { mandarin: "元", pinyin: "yuán", spanish: "yuan" },
  { mandarin: "园", pinyin: "yuán", spanish: "jardín" },
  { mandarin: "原", pinyin: "yuán", spanish: "original" },
  { mandarin: "员", pinyin: "yuán", spanish: "miembro" },
  { mandarin: "远", pinyin: "yuǎn", spanish: "lejos" },
  { mandarin: "院", pinyin: "yuàn", spanish: "patio" },
  { mandarin: "愿", pinyin: "yuàn", spanish: "desear" },
  { mandarin: "约", pinyin: "yuē", spanish: "acordar" },
  { mandarin: "月", pinyin: "yuè", spanish: "luna" },
  { mandarin: "越", pinyin: "yuè", spanish: "sobrepasar" },
  { mandarin: "云", pinyin: "yún", spanish: "nube" },
  { mandarin: "运", pinyin: "yùn", spanish: "suerte" },
  { mandarin: "再", pinyin: "zài", spanish: "otra vez" },
  { mandarin: "在", pinyin: "zài", spanish: "en" },
  { mandarin: "咱", pinyin: "zán", spanish: "nosotros" },
  { mandarin: "脏", pinyin: "zāng", spanish: "sucio" },
  { mandarin: "早", pinyin: "zǎo", spanish: "temprano" },
  { mandarin: "怎", pinyin: "zěn", spanish: "cómo" },
  { mandarin: "站", pinyin: "zhàn", spanish: "estar de pie" },
  { mandarin: "张", pinyin: "zhāng", spanish: "extender" },
  { mandarin: "长", pinyin: "zhǎng", spanish: "crecer" },
  { mandarin: "找", pinyin: "zhǎo", spanish: "buscar" },
  { mandarin: "着", pinyin: "zhe", spanish: "partícula" },
  { mandarin: "真", pinyin: "zhēn", spanish: "verdadero" },
  { mandarin: "争", pinyin: "zhēng", spanish: "disputar" },
  { mandarin: "整", pinyin: "zhěng", spanish: "entero" },
  { mandarin: "正", pinyin: "zhèng", spanish: "recto" },
  { mandarin: "证", pinyin: "zhèng", spanish: "certificado" },
  { mandarin: "政", pinyin: "zhèng", spanish: "gobierno" },
  { mandarin: "之", pinyin: "zhī", spanish: "de" },
  { mandarin: "支", pinyin: "zhī", spanish: "sostener" },
  { mandarin: "知", pinyin: "zhī", spanish: "saber" },
  { mandarin: "织", pinyin: "zhī", spanish: "tejer" },
  { mandarin: "直", pinyin: "zhí", spanish: "derecho" },
  { mandarin: "职", pinyin: "zhí", spanish: "deber" },
  { mandarin: "纸", pinyin: "zhǐ", spanish: "papel" },
  { mandarin: "指", pinyin: "zhǐ", spanish: "dedo" },
  { mandarin: "至", pinyin: "zhì", spanish: "hasta" },
  { mandarin: "治", pinyin: "zhì", spanish: "gobernar" },
  { mandarin: "中", pinyin: "zhōng", spanish: "centro" },
  { mandarin: "终", pinyin: "zhōng", spanish: "final" },
  { mandarin: "种", pinyin: "zhǒng", spanish: "tipo" },
  { mandarin: "重", pinyin: "zhòng", spanish: "pesado" },
  { mandarin: "周", pinyin: "zhōu", spanish: "semana" },
  { mandarin: "洲", pinyin: "zhōu", spanish: "continente" },
  { mandarin: "猪", pinyin: "zhū", spanish: "cerdo" },
  { mandarin: "主", pinyin: "zhǔ", spanish: "dueño" },
  { mandarin: "助", pinyin: "zhù", spanish: "ayudar" },
  { mandarin: "住", pinyin: "zhù", spanish: "vivir" },
  { mandarin: "注", pinyin: "zhù", spanish: "nota" },
  { mandarin: "祝", pinyin: "zhù", spanish: "desear" },
  { mandarin: "装", pinyin: "zhuāng", spanish: "vestir" },
  { mandarin: "准", pinyin: "zhǔn", spanish: "exacto" },
  { mandarin: "桌", pinyin: "zhuō", spanish: "mesa" },
  { mandarin: "着", pinyin: "zhuó", spanish: "poner" },
  { mandarin: "仔", pinyin: "zǐ", spanish: "cuidadoso" },
  { mandarin: "资", pinyin: "zī", spanish: "recursos" },
  { mandarin: "子", pinyin: "zǐ", spanish: "hijo" },
  { mandarin: "自", pinyin: "zì", spanish: "desde" },
  { mandarin: "字", pinyin: "zì", spanish: "carácter" },
  { mandarin: "总", pinyin: "zǒng", spanish: "total" },
  { mandarin: "走", pinyin: "zǒu", spanish: "caminar" },
  { mandarin: "足", pinyin: "zú", spanish: "pie" },
  { mandarin: "族", pinyin: "zú", spanish: "familia" },
  { mandarin: "组", pinyin: "zǔ", spanish: "grupo" },
  { mandarin: "最", pinyin: "zuì", spanish: "más" },
  { mandarin: "昨", pinyin: "zuó", spanish: "ayer" },
  { mandarin: "左", pinyin: "zuǒ", spanish: "izquierda" },
  { mandarin: "作", pinyin: "zuò", spanish: "hacer" },
  { mandarin: "坐", pinyin: "zuò", spanish: "sentarse" },
  { mandarin: "座", pinyin: "zuò", spanish: "asiento" }   
      
    
  ];

  static obtenerAleatoria() {
    const progreso = Progresso.cargar();
    const frasesDisponibles = this.lista.filter(frase => 
      (progreso[frase.mandarin] || 0) < 5
    );
    
    if (frasesDisponibles.length === 0) {
      alert('¡Felicidades mi vida, dominaste todo! 💖');
      return this.lista[0];
    }

    
    return frasesDisponibles[Math.floor(Math.random() * frasesDisponibles.length)];
  }
}