class Progresso {
  static guardar(progreso) {
    localStorage.setItem('progresoChino', JSON.stringify(progreso));
  }

  static cargar() {
    const datos = localStorage.getItem('progresoChino');
    return datos ? JSON.parse(datos) : {};
  }
}

class Frases {
  static lista = [

  { mandarin: "蔼", pinyin: "ǎi", spanish: "amable" },
  { mandarin: "隘", pinyin: "ài", spanish: "estrecho" },
  { mandarin: "庵", pinyin: "ān", spanish: "templo budista" },
  { mandarin: "鞍", pinyin: "ān", spanish: "silla de montar" },
  { mandarin: "熬", pinyin: "áo", spanish: "hervir a fuego lento" },
  { mandarin: "凹", pinyin: "āo", spanish: "cóncavo" },
  { mandarin: "袄", pinyin: "ǎo", spanish: "chaqueta acolchada" },
  { mandarin: "芭", pinyin: "bā", spanish: "plátano" },
  { mandarin: "疤", pinyin: "bā", spanish: "cicatriz" },
  { mandarin: "掰", pinyin: "bāi", spanish: "partir con las manos" },
  { mandarin: "斑", pinyin: "bān", spanish: "mancha" },
  { mandarin: "拌", pinyin: "bàn", spanish: "mezclar" },
  { mandarin: "绑", pinyin: "bǎng", spanish: "atar" },
  { mandarin: "磅", pinyin: "bàng", spanish: "libra (peso)" },
  { mandarin: "镑", pinyin: "bàng", spanish: "libra esterlina" },
  { mandarin: "褒", pinyin: "bāo", spanish: "elogiar" },
  { mandarin: "雹", pinyin: "báo", spanish: "granizo" },
  { mandarin: "泵", pinyin: "bèng", spanish: "bomba" },
  { mandarin: "匕", pinyin: "bǐ", spanish: "cuchillo" },
  { mandarin: "鄙", pinyin: "bǐ", spanish: "despreciable" },
  { mandarin: "毙", pinyin: "bì", spanish: "morir" },
  { mandarin: "弊", pinyin: "bì", spanish: "fraude" },
  { mandarin: "鞭", pinyin: "biān", spanish: "látigo" },
  { mandarin: "贬", pinyin: "biǎn", spanish: "devaluar" },
  { mandarin: "辫", pinyin: "biàn", spanish: "trenza" },
  { mandarin: "彪", pinyin: "biāo", spanish: "valiente" },
  { mandarin: "憋", pinyin: "biē", spanish: "contener" },
  { mandarin: "鳖", pinyin: "biē", spanish: "tortuga" },
  { mandarin: "瘪", pinyin: "biě", spanish: "desinflado" },
  { mandarin: "丙", pinyin: "bǐng", spanish: "tercero" },
  { mandarin: "秉", pinyin: "bǐng", spanish: "sostener" },
  { mandarin: "钵", pinyin: "bō", spanish: "cuenco" },
  { mandarin: "卜", pinyin: "bo", spanish: "adivinar" },
  { mandarin: "哺", pinyin: "bǔ", spanish: "alimentar" },
  { mandarin: "埠", pinyin: "bù", spanish: "puerto" },
  { mandarin: "簿", pinyin: "bù", spanish: "libro de registros" },
  { mandarin: "睬", pinyin: "cǎi", spanish: "prestar atención" },
  { mandarin: "惭", pinyin: "cán", spanish: "avergonzado" },
  { mandarin: "惨", pinyin: "cǎn", spanish: "triste" },
  { mandarin: "舱", pinyin: "cāng", spanish: "cabina" },
  { mandarin: "糙", pinyin: "cāo", spanish: "áspero" },
  { mandarin: "厕", pinyin: "cè", spanish: "baño" },
  { mandarin: "蹭", pinyin: "cèng", spanish: "frotar" },
  { mandarin: "诧", pinyin: "chà", spanish: "sorprendido" },
  { mandarin: "钗", pinyin: "chāi", spanish: "horquilla" },
  { mandarin: "掺", pinyin: "chān", spanish: "mezclar" },
  { mandarin: "禅", pinyin: "chán", spanish: "meditación" },
  { mandarin: "昌", pinyin: "chāng", spanish: "próspero" },
  { mandarin: "猖", pinyin: "chāng", spanish: "feroz" },
  { mandarin: "裳", pinyin: "cháng", spanish: "faldas" },
  { mandarin: "嘲", pinyin: "cháo", spanish: "burlarse" },
  { mandarin: "澈", pinyin: "chè", spanish: "claro" },
  { mandarin: "臣", pinyin: "chén", spanish: "ministro" },
  { mandarin: "辰", pinyin: "chén", spanish: "tiempo" },
  { mandarin: "忱", pinyin: "chén", spanish: "sinceridad" },
  { mandarin: "秤", pinyin: "chèng", spanish: "balanza" },
  { mandarin: "痴", pinyin: "chī", spanish: "obsesionado" },
  { mandarin: "弛", pinyin: "chí", spanish: "relajado" },
  { mandarin: "耻", pinyin: "chǐ", spanish: "vergüenza" },
  { mandarin: "宠", pinyin: "chǒng", spanish: "consentir" },
  { mandarin: "畴", pinyin: "chóu", spanish: "tipo" },
  { mandarin: "稠", pinyin: "chóu", spanish: "denso" },
  { mandarin: "锄", pinyin: "chú", spanish: "azada" },
  { mandarin: "雏", pinyin: "chú", spanish: "cría" },
  { mandarin: "橱", pinyin: "chú", spanish: "armario" },
  { mandarin: "矗", pinyin: "chù", spanish: "erguido" },
  { mandarin: "揣", pinyin: "chuǎi", spanish: "estimar" },
  { mandarin: "囱", pinyin: "cōng", spanish: "chimenea" },
  { mandarin: "挫", pinyin: "cuò", spanish: "frustrar" },
  { mandarin: "瘩", pinyin: "da", spanish: "bulto" },
  { mandarin: "歹", pinyin: "dǎi", spanish: "malvado" },
  { mandarin: "贷", pinyin: "dài", spanish: "préstamo" },
  { mandarin: "耽", pinyin: "dān", spanish: "retrasar" },
  { mandarin: "档", pinyin: "dàng", spanish: "archivo" },
  { mandarin: "叨", pinyin: "dāo", spanish: "parlotear" },
  { mandarin: "捣", pinyin: "dǎo", spanish: "machacar" },
  { mandarin: "祷", pinyin: "dǎo", spanish: "rezar" },
  { mandarin: "悼", pinyin: "dào", spanish: "lamentar" },
  { mandarin: "嘀", pinyin: "dí", spanish: "gotear" },
  { mandarin: "嫡", pinyin: "dí", spanish: "legítimo" },
  { mandarin: "邸", pinyin: "dǐ", spanish: "residencia" },
  { mandarin: "蒂", pinyin: "dì", spanish: "tallo" },
  { mandarin: "颠", pinyin: "diān", spanish: "cima" },
  { mandarin: "碘", pinyin: "diǎn", spanish: "yodo" },
  { mandarin: "佃", pinyin: "diàn", spanish: "arrendar" },
  { mandarin: "淀", pinyin: "diàn", spanish: "sedimento" },
  { mandarin: "碟", pinyin: "dié", spanish: "plato pequeño" },
  { mandarin: "鼎", pinyin: "dǐng", spanish: "caldero" },
  { mandarin: "董", pinyin: "dǒng", spanish: "director" },
  { mandarin: "栋", pinyin: "dòng", spanish: "viga" },
  { mandarin: "窦", pinyin: "dòu", spanish: "agujero" },
  { mandarin: "睹", pinyin: "dǔ", spanish: "presenciar" },
  { mandarin: "妒", pinyin: "dù", spanish: "envidiar" },
  { mandarin: "缎", pinyin: "duàn", spanish: "satén" },
  { mandarin: "兑", pinyin: "duì", spanish: "cambiar" },
  { mandarin: "墩", pinyin: "dūn", spanish: "bloque" },
  { mandarin: "盹", pinyin: "dǔn", spanish: "siesta" },
  { mandarin: "咄", pinyin: "duō", spanish: "autoritario" },
  { mandarin: "哆", pinyin: "duō", spanish: "temblar" },
  { mandarin: "踱", pinyin: "duó", spanish: "pasear" },
  { mandarin: "垛", pinyin: "duǒ", spanish: "montón" },
  { mandarin: "堕", pinyin: "duò", spanish: "caer" },
  { mandarin: "讹", pinyin: "é", spanish: "erróneo" },
  { mandarin: "娥", pinyin: "é", spanish: "bella" },
  { mandarin: "厄", pinyin: "è", spanish: "desastre" },
  { mandarin: "遏", pinyin: "è", spanish: "contener" },
  { mandarin: "愕", pinyin: "è", spanish: "sorprendido" },
  { mandarin: "饵", pinyin: "ěr", spanish: "cebo" },
  { mandarin: "贰", pinyin: "èr", spanish: "dos (formal)" },
  { mandarin: "筏", pinyin: "fá", spanish: "balsa" },
  { mandarin: "矾", pinyin: "fán", spanish: "alumbre" },
  { mandarin: "妃", pinyin: "fēi", spanish: "concubina" },
  { mandarin: "匪", pinyin: "fěi", spanish: "bandido" },
  { mandarin: "诽", pinyin: "fěi", spanish: "difamar" },
  { mandarin: "吠", pinyin: "fèi", spanish: "ladrar" },
  { mandarin: "吩", pinyin: "fēn", spanish: "ordenar" },
  { mandarin: "氛", pinyin: "fēn", spanish: "atmósfera" },
  { mandarin: "焚", pinyin: "fén", spanish: "quemar" },
  { mandarin: "忿", pinyin: "fèn", spanish: "indignado" },
  { mandarin: "讽", pinyin: "fěng", spanish: "satirizar" },
  { mandarin: "敷", pinyin: "fū", spanish: "aplicar" },
  { mandarin: "芙", pinyin: "fú", spanish: "lotus" },
  { mandarin: "拂", pinyin: "fú", spanish: "sacudir" },
  { mandarin: "俘", pinyin: "fú", spanish: "cautivo" },
  { mandarin: "甫", pinyin: "fǔ", spanish: "recién" },
  { mandarin: "斧", pinyin: "fǔ", spanish: "hacha" },
  { mandarin: "俯", pinyin: "fǔ", spanish: "inclinarse" },
  { mandarin: "咐", pinyin: "fù", spanish: "instruir" },
  { mandarin: "缚", pinyin: "fù", spanish: "atar" },
  { mandarin: "尬", pinyin: "gà", spanish: "incómodo" },
  { mandarin: "丐", pinyin: "gài", spanish: "mendigo" },
  { mandarin: "柑", pinyin: "gān", spanish: "mandarina" },
  { mandarin: "竿", pinyin: "gān", spanish: "palo" },
  { mandarin: "尴", pinyin: "gān", spanish: "vergonzoso" },
  { mandarin: "橄", pinyin: "gǎn", spanish: "aceituna" },
  { mandarin: "擀", pinyin: "gǎn", spanish: "estirar masa" },
  { mandarin: "赣", pinyin: "gàn", spanish: "Jiangxi" },
  { mandarin: "冈", pinyin: "gāng", spanish: "cresta" },
  { mandarin: "肛", pinyin: "gāng", spanish: "anal" },
  { mandarin: "杠", pinyin: "gàng", spanish: "barra" },
  { mandarin: "羔", pinyin: "gāo", spanish: "cordero" },
  { mandarin: "膏", pinyin: "gāo", spanish: "ungüento" },
  { mandarin: "糕", pinyin: "gāo", spanish: "pastel" },
  { mandarin: "镐", pinyin: "gǎo", spanish: "pico" },
  { mandarin: "疙", pinyin: "gē", spanish: "bulto" },
  { mandarin: "庚", pinyin: "gēng", spanish: "séptimo" },
  { mandarin: "羹", pinyin: "gēng", spanish: "sopa espesa" },
  { mandarin: "耿", pinyin: "gěng", spanish: "honesto" },
  { mandarin: "躬", pinyin: "gōng", spanish: "personalmente" },
  { mandarin: "蚣", pinyin: "gōng", spanish: "ciempiés" },
  { mandarin: "汞", pinyin: "gǒng", spanish: "mercurio" },
  { mandarin: "苟", pinyin: "gǒu", spanish: "indigno" },
  { mandarin: "垢", pinyin: "gòu", spanish: "suciedad" },
  { mandarin: "沽", pinyin: "gū", spanish: "comprar" },
  { mandarin: "辜", pinyin: "gū", spanish: "culpa" },
  { mandarin: "雇", pinyin: "gù", spanish: "contratar" },
  { mandarin: "寡", pinyin: "guǎ", spanish: "viuda" },
  { mandarin: "卦", pinyin: "guà", spanish: "adivinación" },
  { mandarin: "棺", pinyin: "guān", spanish: "ataúd" },
  { mandarin: "盥", pinyin: "guàn", spanish: "lavar" },
  { mandarin: "逛", pinyin: "guàng", spanish: "pasear" },
  { mandarin: "硅", pinyin: "guī", spanish: "silicio" },
  { mandarin: "闺", pinyin: "guī", spanish: "dormitorio femenino" },
  { mandarin: "瑰", pinyin: "guī", spanish: "raro" },
  { mandarin: "诡", pinyin: "guǐ", spanish: "engañoso" },
  { mandarin: "癸", pinyin: "guǐ", spanish: "décimo" },
  { mandarin: "跪", pinyin: "guì", spanish: "arrodillarse" },
  { mandarin: "辊", pinyin: "gǔn", spanish: "rodillo" },
  { mandarin: "裹", pinyin: "guǒ", spanish: "envolver" },
  { mandarin: "骸", pinyin: "hái", spanish: "esqueleto" },
  { mandarin: "骇", pinyin: "hài", spanish: "asustar" },
  { mandarin: "酣", pinyin: "hān", spanish: "embriagado" },
  { mandarin: "憨", pinyin: "hān", spanish: "ingenuo" },
  { mandarin: "涵", pinyin: "hán", spanish: "contener" },
  { mandarin: "悍", pinyin: "hàn", spanish: "audaz" },
  { mandarin: "焊", pinyin: "hàn", spanish: "soldar" },
  { mandarin: "捍", pinyin: "hàn", spanish: "defender" },
  { mandarin: "翰", pinyin: "hàn", spanish: "pluma" },
  { mandarin: "憾", pinyin: "hàn", spanish: "lamentar" },
  { mandarin: "撼", pinyin: "hàn", spanish: "sacudir" },
  { mandarin: "翰", pinyin: "hàn", spanish: "escritura" },
  { mandarin: "壕", pinyin: "háo", spanish: "trinchera" },
  { mandarin: "嚎", pinyin: "háo", spanish: "aullar" },
  { mandarin: "皓", pinyin: "hào", spanish: "blanco brillante" },
  { mandarin: "禾", pinyin: "hé", spanish: "cereal" },
  { mandarin: "哼", pinyin: "hēng", spanish: "gruñir" },
  { mandarin: "亨", pinyin: "hēng", spanish: "próspero" },
  { mandarin: "弘", pinyin: "hóng", spanish: "amplio" },
  { mandarin: "弧", pinyin: "hú", spanish: "arco" },
  { mandarin: "唬", pinyin: "hǔ", spanish: "asustar" },
  { mandarin: "沪", pinyin: "hù", spanish: "Shanghái" },
  { mandarin: "哗", pinyin: "huá", spanish: "ruidoso" },
  { mandarin: "猾", pinyin: "huá", spanish: "astuto" },
  { mandarin: "徊", pinyin: "huái", spanish: "dudar" },
  { mandarin: "淮", pinyin: "huái", spanish: "río Huai" },
  { mandarin: "槐", pinyin: "huái", spanish: "acacia" },
  { mandarin: "宦", pinyin: "huàn", spanish: "funcionario" },
  { mandarin: "涣", pinyin: "huàn", spanish: "dispersar" },
  { mandarin: "焕", pinyin: "huàn", spanish: "brillante" },
  { mandarin: "痪", pinyin: "huàn", spanish: "parálisis" },
  { mandarin: "凰", pinyin: "huáng", spanish: "fénix hembra" },
  { mandarin: "惶", pinyin: "huáng", spanish: "atemorizado" },
  { mandarin: "蝗", pinyin: "huáng", spanish: "langosta" },
  { mandarin: "簧", pinyin: "huáng", spanish: "resorte" },
  { mandarin: "恍", pinyin: "huǎng", spanish: "de repente" },
  { mandarin: "谎", pinyin: "huǎng", spanish: "mentira" },
  { mandarin: "幌", pinyin: "huǎng", spanish: "cortina" },
  { mandarin: "卉", pinyin: "huì", spanish: "plantas" },
  { mandarin: "讳", pinyin: "huì", spanish: "tabú" },
  { mandarin: "贿", pinyin: "huì", spanish: "soborno" },
  { mandarin: "秽", pinyin: "huì", spanish: "sucio" },
  { mandarin: "慧", pinyin: "huì", spanish: "sabio" },
  { mandarin: "荤", pinyin: "hūn", spanish: "carne" },
  { mandarin: "豁", pinyin: "huō", spanish: "abrir" },
  { mandarin: "惑", pinyin: "huò", spanish: "confundir" },
  { mandarin: "讥", pinyin: "jī", spanish: "ridiculizar" },
  { mandarin: "叽", pinyin: "jī", spanish: "gorjear" },
  { mandarin: "唧", pinyin: "jī", spanish: "bomba de agua" },
  { mandarin: "缉", pinyin: "jī", spanish: "arrestar" },
  { mandarin: "畸", pinyin: "jī", spanish: "anormal" },
  { mandarin: "箕", pinyin: "jī", spanish: "criba" },
  { mandarin: "稽", pinyin: "jī", spanish: "verificar" },
  { mandarin: "棘", pinyin: "jí", spanish: "espinoso" },
  { mandarin: "嫉", pinyin: "jí", spanish: "envidiar" },
  { mandarin: "脊", pinyin: "jǐ", spanish: "columna vertebral" },
  { mandarin: "伎", pinyin: "jì", spanish: "talento" },
  { mandarin: "祭", pinyin: "jì", spanish: "sacrificar" },
  { mandarin: "鲫", pinyin: "jì", spanish: "carpa" },
  { mandarin: "颊", pinyin: "jiá", spanish: "mejilla" },
  { mandarin: "贾", pinyin: "jiǎ", spanish: "comerciante" },
  { mandarin: "钾", pinyin: "jiǎ", spanish: "potasio" },
  { mandarin: "稼", pinyin: "jià", spanish: "cosechar" },
  { mandarin: "奸", pinyin: "jiān", spanish: "traidor" },
  { mandarin: "歼", pinyin: "jiān", spanish: "aniquilar" },
  { mandarin: "煎", pinyin: "jiān", spanish: "freír" },
  { mandarin: "拣", pinyin: "jiǎn", spanish: "escoger" },
  { mandarin: "俭", pinyin: "jiǎn", spanish: "frugal" },
  { mandarin: "柬", pinyin: "jiǎn", spanish: "tarjeta" },
  { mandarin: "茧", pinyin: "jiǎn", spanish: "capullo" },
  { mandarin: "捡", pinyin: "jiǎn", spanish: "recoger" },
  { mandarin: "荐", pinyin: "jiàn", spanish: "recomendar" },
  { mandarin: "贱", pinyin: "jiàn", spanish: "barato" },
  { mandarin: "涧", pinyin: "jiàn", spanish: "barranco" },
  { mandarin: "溅", pinyin: "jiàn", spanish: "salpicar" },
  { mandarin: "僵", pinyin: "jiāng", spanish: "rígido" },
  { mandarin: "缰", pinyin: "jiāng", spanish: "rienda" },
  { mandarin: "桨", pinyin: "jiǎng", spanish: "remo" },
  { mandarin: "酱", pinyin: "jiàng", spanish: "salsa" },
  { mandarin: "椒", pinyin: "jiāo", spanish: "pimienta" },
  { mandarin: "跤", pinyin: "jiāo", spanish: "caída" },
  { mandarin: "蕉", pinyin: "jiāo", spanish: "plátano" },
  { mandarin: "侥", pinyin: "jiǎo", spanish: "afortunado" },
  { mandarin: "狡", pinyin: "jiǎo", spanish: "astuto" },
  { mandarin: "饺", pinyin: "jiǎo", spanish: "empanadilla" },
  { mandarin: "绞", pinyin: "jiǎo", spanish: "torsión" },
  { mandarin: "矫", pinyin: "jiǎo", spanish: "corregir" },
  { mandarin: "剿", pinyin: "jiǎo", spanish: "exterminar" },
  { mandarin: "缴", pinyin: "jiǎo", spanish: "pagar" },
  { mandarin: "窖", pinyin: "jiào", spanish: "bodega" },
  { mandarin: "酵", pinyin: "jiào", spanish: "fermentar" },
  { mandarin: "秸", pinyin: "jiē", spanish: "paja" },
  { mandarin: "劫", pinyin: "jié", spanish: "robar" },
  { mandarin: "睫", pinyin: "jié", spanish: "pestaña" },
  { mandarin: "芥", pinyin: "jiè", spanish: "mostaza" },
  { mandarin: "诫", pinyin: "jiè", spanish: "advertir" },
  { mandarin: "藉", pinyin: "jiè", spanish: "pretexto" },
  { mandarin: "巾", pinyin: "jīn", spanish: "toalla" },
  { mandarin: "筋", pinyin: "jīn", spanish: "tendón" },
  { mandarin: "襟", pinyin: "jīn", spanish: "sisa" },
  { mandarin: "谨", pinyin: "jǐn", spanish: "cauteloso" },
  { mandarin: "荆", pinyin: "jīng", spanish: "espina" },
  { mandarin: "兢", pinyin: "jīng", spanish: "cauteloso" },
  { mandarin: "靖", pinyin: "jìng", spanish: "pacífico" },
  { mandarin: "窘", pinyin: "jiǒng", spanish: "avergonzado" },
  { mandarin: "揪", pinyin: "jiū", spanish: "tirar" },
  { mandarin: "灸", pinyin: "jiǔ", spanish: "moxibustión" },
  { mandarin: "玖", pinyin: "jiǔ", spanish: "nueve" },
  { mandarin: "韭", pinyin: "jiǔ", spanish: "puerro" },
  { mandarin: "臼", pinyin: "jiù", spanish: "mortero" },
  { mandarin: "疚", pinyin: "jiù", spanish: "remordimiento" },
  { mandarin: "拘", pinyin: "jū", spanish: "detener" },
  { mandarin: "驹", pinyin: "jū", spanish: "potro" },
  { mandarin: "鞠", pinyin: "jū", spanish: "inclinarse" },
  { mandarin: "沮", pinyin: "jǔ", spanish: "desanimado" },
  { mandarin: "俱", pinyin: "jù", spanish: "todos" },
  { mandarin: "炬", pinyin: "jù", spanish: "antorcha" },
  { mandarin: "锯", pinyin: "jù", spanish: "sierra" },
  { mandarin: "鹃", pinyin: "juān", spanish: "cuco" },
  { mandarin: "眷", pinyin: "juàn", spanish: "familia" },
  { mandarin: "诀", pinyin: "jué", spanish: "fórmula" },
  { mandarin: "抉", pinyin: "jué", spanish: "escoger" },
  { mandarin: "倔", pinyin: "jué", spanish: "terco" },
  { mandarin: "钧", pinyin: "jūn", spanish: "medida" }
 
    
  ];

  static obtenerAleatoria() {
    const progreso = Progresso.cargar();
    const frasesDisponibles = this.lista.filter(frase => 
      (progreso[frase.mandarin] || 0) < 5
    );
    
    if (frasesDisponibles.length === 0) {
      alert('¡Felicidades mi vida, dominaste todo! 💖');
      return this.lista[0];
    }

    
    return frasesDisponibles[Math.floor(Math.random() * frasesDisponibles.length)];
  }
}